### ISSUE TITLE
Bring back "custom module" guide?

### ISSUE THREAD

**Issue by ameotoko** [contao/docs#1072]
When I just started with Contao, [this guide](https://github.com/contao/docs-archive/tree/main/cookbook/en/custom-module) from the old Cookbook has helped me a lot in understanding basic concepts and building blocks of Contao, and how it is generally pieced together.

Should we maybe bring it back? I could try to rewrite it for Contao >= 4.13

**Comment by fritzmg** [comment]
What is missing in the current docs?

**Comment by ameotoko** [comment]
This was just a thought, I don't think anything specific is missing.

**Comment by fritzmg** [comment]
Imho the paradigm has changed with Contao 4 and such a guide is not really needed.

**Comment by ameotoko** [comment]
Ok, this can be closed then.
