### ISSUE TITLE
Change of wording needed

### ISSUE THREAD

**Issue by fiedsch** [contao/docs#113]
In 

> If you are working with Contao fragments such as content elements, front end modules etc. not that you may want to extend the Contao\CoreBundle\Controller\AbstractFragmentController and use the tagResponse() method of it for convenience.

(see https://github.com/contao/docs/blame/master/docs/dev/framework/caching.md#L163-L165)
I think "not that" should be "note that" or be completely removed.

**Comment by fritzmg** [comment]
See #115
