### ISSUE TITLE
Search shows no result text

### ISSUE THREAD

**Issue by koertho** [contao/docs#1167]
The new documentation search shows no result texts for me:

![image](https://user-images.githubusercontent.com/12064642/228276556-72ef9090-043f-4be7-8975-c8888fefd318.png)

Tested browsers: Chrome 111.0.5563.110 (Linux Mint 20.3), Firefox 111.0 (Linux Mint 20.3), Chrome 111 (Android)

**Comment by koertho** [comment]
Habe es gerade im Slack gelesen: Wohl ein Bug in der Such-Engine: https://github.com/algolia/docsearch/issues/1839

**Comment by fritzmg** [comment]
Fixed now :)
