### ISSUE TITLE
small typo found

### ISSUE THREAD

**Issue by magicsepp** [contao/docs#1178]
https://docs.contao.org/manual/en/system/settings/#different-e-mail-configurations-and-sender-addresses

The Swiftmaielr Bundle is not available anymore by default since Contao 4.10. Instead the [Symfony Mailer](https://symfony.com/doc/4.4/mailer.html#transport-setup) component is used. In order to send emails asynchronously in this case we can make use of the [Symfony Messenger](https://symfony.com/doc/current/messenger.html) component, which must be installed first via Composer:

should be: 
The Swiftmailer Bundle 

Many thanks

**Comment by netzarbeiter** [comment]
It would be nice if you could [support us](https://docs.contao.org/manual/de/beitragen/) with a pull request.

**Comment by Santhoshmani1** [comment]
Hello @netzarbeiter  
I have fixed the Typo issue please check the pr attached to the issue.
Thanks
