### ISSUE TITLE
Twig templates are marked as experimental

### ISSUE THREAD

**Issue by JanMalte** [contao/docs#1179]
With contao v5 the default template engine changed to `twig`.

https://docs.contao.org/manual/de/migration/#templates

The documentation about the templates has still a warning about the experimental stage of `twig` templates.

https://docs.contao.org/manual/de/layout/templates/twig/

**Comment by netzarbeiter** [comment]
We are currently making final corrections.
https://github.com/contao/docs/pull/1176
