### ISSUE TITLE
Manager Wiki in Doku überführen?

### ISSUE THREAD

**Issue by contaoacademy** [contao/docs#1198]
Unter dem GitHub Repository gibt es ein Wiki bezüglicher der Hoster.
https://github.com/contao/contao-manager/wiki

Wäre es sinnvoll, diesen Bereich in die Doku zu integrieren?

**Comment by netzarbeiter** [comment]
Sind diese Daten noch relevant und nicht veraltet?

Vielleicht einfach ein Text mit Link zum Wiki:

Bei den nachfolgenden Hosting-Anbietern wurde der Contao Manager getestet. Eventuelle Probleme sowie deren Lösungen sind auf den jeweiligen Unterseiten vermerkt. [zum Wiki](https://github.com/contao/contao-manager/wiki)

**Comment by contaoacademy** [comment]
Wir haben auf dem Camp festgestellt, dass dieses Wiki hier kaum jemand kennt. Die Informationen sind auf jeden Fall nicht aktuell. Die Frage ist, wie wir mit nun damit umgehen wollen.
Wichtig und relevant oder eher irreführend und komplett entfernen?

Es wäre sicher schöner, die Doku als einzigen Anlaufpunkt zu haben, dafür müssten allerdings die Informationen geprüft werden. Das ist sicher nicht ohne fremde Hilfe möglich.

@fritzmg @aschempp

**Comment by netzarbeiter** [comment]
Ich möchte eigentlich keine Hoster in der Doku, da es wie eine Empfehlung rüberkommen kann.

**Comment by contaoacademy** [comment]
> Ich möchte eigentlich keine Hoster in der Doku, da es wie eine Empfehlung rüberkommen kann.
Damit kann ich auch gut leben.

Es braucht nur noch die Entscheidung:
a) nix machen, so lassen
b) verlinken

**Comment by aschempp** [comment]
Die Informationen sind nicht mehr aktuell weil sie nur sehr begrenzt genutzt werden. Sie waren früher relevant, als man seinen Hoster auswählen musste. Und heute benutzen wir die PHP-Pfade welche hier dokumentiert sind als Grundlage für die automatische Erkennung. Ich würde es einfach so lassen, aber wenn jemand Lust hat gerne das Intro anpassen 🙃

**Comment by contaoacademy** [comment]
@aschempp Ich kann gerne das Intro anpassen. Ich mach mal einen Vorschlag ;-)

**Comment by aschempp** [comment]
es ist ein Wiki, du kannst einfach reinschreiben 😆

**Comment by contaoacademy** [comment]
Ich hab schon reingeschrieben und deswegen auch das Ticket geschlossen.
