### ISSUE TITLE
Fehlende Bilder in der Doku

### ISSUE THREAD

**Issue by contaoacademy** [contao/docs#1201]
Folgende Bilder fehlen in der Doku:

| Seite  | Bild
|-------|-------|
| https://docs.contao.org/manual/de/installation/contao-aktualisieren/ | https://docs.contao.org/manual/de/installation/images/de/aktualisierung-fuer-minor-release-starten.png |
| https://docs.contao.org/manual/de/installation/contao-aktualisieren/ | https://docs.contao.org/manual/de/installation/images/de/aktualisierung-fuer-minor-release-abgeschlossen.png |
| https://docs.contao.org/manual/de/installation/erweiterungen-installieren/ | https://docs.contao.org/manual/de/installation/images/de/erweiterungssuche-extensions-contao-org.png |
| https://docs.contao.org/manual/de/installation/contao-installtool/ | https://docs.contao.org/manual/de/installation/images/de/datenbankverbindung-fuer-contao-eingeben.png |
| https://docs.contao.org/manual/de/installation/contao-installtool/ | https://docs.contao.org/manual/de/installation/images/de/datenbankaenderungen-bestaetigen.png |
| https://docs.contao.org/manual/de/installation/contao-installtool/ | https://docs.contao.org/manual/de/installation/images/de/das-installtool-zuruecksetzen.png |
| https://docs.contao.org/manual/en/installation/install-extensions/ | https://docs.contao.org/manual/de/installation/images/en/extensions-contao-org.png |
| https://docs.contao.org/manual/en/core-extensions/newsletter/newsletter-management/ | https://docs.contao.org/manual/de/core-extensions/newsletter/images/en/activate_recipients.png |
| https://docs.contao.org/manual/en/extensions/contao-easy_themes/ | https://docs.contao.org/manual/de/extensions/images/en/contao-easy_themes-mode-back-end-module-with-reference.png |

**Comment by netzarbeiter** [comment]
Thank you, Christian
