### ISSUE TITLE
Wrong schema markup on the FAQ page

### ISSUE THREAD

**Issue by leofeyer** [contao/docs#1209]
![](https://github.com/contao/docs/assets/1192057/9cc4fdfb-3d63-40df-be74-0e1eec843ff5)

There are multiple `"@type": "FAQPage"` entries in the FAQ list on https://docs.contao.org/manual/en/faq/.

**Comment by fritzmg** [comment]
@Metis77 we will need to revert https://github.com/contao/docs/pull/1203 unfortunately. We need to find a way to collect the meta data and then output them in one JSON-LD.

**Comment by Metis77** [comment]
Oh thats strange.
When I tested this before the PR with the google rich snippet tester, it was ok.

However combining the FAQs in one entry would be much better, anyway.
Sorrily I am not sure, how to accomplish that wit hugo.

**Comment by fritzmg** [comment]
I think we can use [`.Scratch`](https://gohugo.io/functions/scratch/) - however I am having troubles storing an array of FAQ entries there (see https://discourse.gohugo.io/t/creating-an-array-of-maps-in-scratch/44677). See https://github.com/contao/docs/pull/1210

**Comment by fritzmg** [comment]
Closing in favor of #1210

**Comment by fritzmg** [comment]
@leofeyer should be fine now: https://search.google.com/test/rich-results?url=https%3A%2F%2Fdocs.contao.org%2Fmanual%2Fde%2Ffaq%2F
