### ISSUE TITLE
Abgeschaltete Doku online

### ISSUE THREAD

**Issue by akroii** [contao/docs#124]
Wenn ich nach `Contao Insert Tags` google, erscheint: https://docs.contao.org/books/manual/4.4/de/04-inhalte-verwalten/inserttags.html

Diese Version ist jedoch Outdated, da es ja die neue Doku gibt: https://docs.contao.org/manual/de/artikelverwaltung/insert-tags/

Auf Contao org ist der Link zur neuen Version verlinkt:
https://docs.contao.org/

Kann man die alte Doku zur neuen redirecten?

**Comment by fritzmg** [comment]
@leofeyer Ticket bitte zu `contao/docs` verschieben

**Comment by Mynyx** [comment]
Die alte Dokumentation sollte meiner Meinung nach nicht offline genommen werden, vielleicht kann dort ein Hinweis auf die neue Dokumentation eingeblendet werden?

Die Anzeige in den Suchergebnissen wird sich mit der Zeit vermutlich von alleine regeln.

**Comment by fritzmg** [comment]
Offline genommen ist die alte Dokumentation nicht, aber ich habe nun für einige Dinge Redirects eingerichtet. Das wird mit der Zeit erweitert.
