### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by contaoacademy** [contao/docs#1243]
Some of the pictures are not shown in the docs.

url | link text | On page
-- | -- | --
https://docs.contao.org/dev/framework/images/twig-file-autocompletion.png?classes=shadow | [alt]: Getting autocompletion for template names | https://docs.contao.org/dev/framework/templates/debugging/
https://docs.contao.org/dev/framework/images/twig-type-autocompletion.png?classes=shadow | [alt]: Getting autocompletion on variables | https://docs.contao.org/dev/framework/templates/debugging/
https://docs.contao.org/dev/framework/images/twig-dump.png?classes=shadow | [alt]: Dumping inside the markup | https://docs.contao.org/dev/framework/templates/debugging/
https://docs.contao.org/dev/framework/images/twig-web-debug-toolbar.png?classes=shadow | [alt]: Dumping into the Symfony Web Debug Toolbar | https://docs.contao.org/dev/framework/templates/debugging/
https://docs.contao.org/dev/framework/images/twig-debugging-breakpoint.png?classes=shadow | [alt]: Directly debugging a Twig template | https://docs.contao.org/dev/framework/templates/debugging/
https://docs.contao.org/manual/en/layout/site-structure/pages-as-central-elements/Plus.svg?classes=icon | [alt]: Open area | https://docs.contao.org/manual/en/layout/site-structure/pages-as-central-elements/
https://docs.contao.org/manual/en/layout/site-structure/pages-as-central-elements/Minus.svg?classes=icon | [alt]: Close area | https://docs.contao.org/manual/en/layout/site-structure/pages-as-central-elements/
https://docs.contao.org/manual/en/layout/theme-manager/manage-stylesheets/_export.svg?classes=icon | [alt]: Export style sheet | https://docs.contao.org/manual/en/layout/theme-manager/manage-stylesheets/
https://docs.contao.org/manual/en/extensions/contao-easy_themes/ end-module-with-reference.png?classes=shadow | [alt]: EasyTheme mode: Back end modules (with selection of a reference group) | https://docs.contao.org/manual/en/extensions/contao-easy_themes/
https://docs.contao.org/manual/en/extensions/contao-easy_themes/ end-module-with-reference.png?classes=shadow | [alt]: EasyTheme mode: Back end modules (with selection of a reference group) | https://docs.contao.org/manual/en/extensions/contao-easy_themes/?classes=shadow
https://docs.contao.org/manual/de/layout/seitenstruktur/seiten-als-zentrale-elemente/Plus.svg?classes=icon | [alt]: Bereich öffnen | https://docs.contao.org/manual/de/layout/seitenstruktur/seiten-als-zentrale-elemente/
https://docs.contao.org/manual/de/layout/seitenstruktur/seiten-als-zentrale-elemente/Minus.svg?classes=icon | [alt]: Bereich schließen | https://docs.contao.org/manual/de/layout/seitenstruktur/seiten-als-zentrale-elemente/
https://docs.contao.org/manual/de/layout/theme-manager/stylesheets-verwalten/_export.svg?classes=icon | [alt]: Stylesheet exportieren | https://docs.contao.org/manual/de/layout/theme-manager/stylesheets-verwalten/

**Comment by netzarbeiter** [comment]
Thank you, @contaoacademy
