### ISSUE TITLE
Entwicklermodus

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#126]
Folgende Dinge beschreiben:

* Möglichkeiten (kein Asset Combining, Symfony Toolbar, Fehleranalyse über Stack Traces)
* Aktivierung über Command Line (Contao 4.4)
* Aktivierung über Contao Manager (Contao 4.5 bis 4.7)
* Aktivierung über Contao Manager (ab Contao 4.8)
* Aktivierung über Umgebungsvariable (ab Contao 4.8)

**Comment by xchs** [comment]
- Aktivierung über das Contao Backend (ab Contao 4.8) 😃

**Comment by fritzmg** [comment]
See https://github.com/contao/docs/pull/128
