### ISSUE TITLE
Reversed behaviour of "Click to edit" in Contao 5

### ISSUE THREAD

**Issue by ameotoko** [contao/docs#1279]
Follow up to https://github.com/contao/docs/pull/1051#issuecomment-1171101029

https://docs.contao.org/manual/en/administration-area/back-end-keyboard-shortcuts/#click-to-edit should be updated to reflect changes in Contao 5. What is the proper way to do it?

- add a notice that it's reversed since 5.x
- document as 5.x and add a notice that it was reversed in prior versions

**Comment by fritzmg** [comment]
Just use two tabs: Contao 4, Contao 5+. The description for Contao 5+ should imho be:

* `[Ctrl] + click`: edit the element
* `[Ctrl] + [Shift] + click`: edit the element's children

**Comment by ameotoko** [comment]
Which tab should be the default one? I'd say Contao 5.
