### ISSUE TITLE
Basic Entities

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#129]
In Contao können folgende "Basic Entities" gesetzt werden, die dann in die jeweiligen HTML Entities zurück umgewandelt werden:

* `[&]` für `&amp;`
* `[lt]` für `&lt;`
* `[gt]` für `&gt;`
* `[nbsp]` für `&nbsp;`
* `[-]` für `&shy;`

Diese sollten auch noch dokumentiert werden.

**Comment by fritzmg** [comment]
@netzarbeiter evt. einfach bei den Insert-Tag, weil das ja ein ähnliches Konzept ist? Ich bin mir nicht mal sicher, ob diese Zeichenfolgen überhaupt einen offiziellen Namen innerhalb von Contao haben.

**Comment by Toflar** [comment]
> ob diese Zeichenfolgen überhaupt einen offiziellen Namen innerhalb von Contao haben.

Ja, "basic entities" wie du selber schreibst :D
