### ISSUE TITLE
Contao Docs Update: Evaluation basicEntities for Contao 5

### ISSUE THREAD

**Issue by minstyle** [contao/docs#1370]
As discussed in Slack (https://contao.slack.com/archives/CK4J0KNDB/p1712743045932659), there is probably a new DCA attribute `['eval']['basicEntities']` as of Contao 5.

Please refer to the Contao documentation under:
https://docs.contao.org/dev/reference/dca/fields/#evaluation

**Comment by ausi** [comment]
`'eval' => ['basicEntities' => true]` was added in https://github.com/contao/contao/pull/4453 and is handled in the `Widget` base class here: https://github.com/contao/contao/blob/2c84decd5a81e16a508186060733bdf5deeb43be/core-bundle/contao/library/Contao/Widget.php#L1263-L1266

**Comment by fritzmg** [comment]
See #1373
