### ISSUE TITLE
Document new `InsertTagsSystem` `[Contao ^5.2.x]`

### ISSUE THREAD

**Issue by zoglo** [contao/docs#1379]
### Description

The following PRs:

- https://github.com/contao/contao/pull/4779
- https://github.com/contao/contao/pull/6195 

included a new insert-tags-system in Contao ```5.2+```. It apparently allows registering insert tags via PHP Annotations.

### Examples

**Normal usage**

```php
#[AsInsertTag('link_url')]
```
Code example:
https://github.com/contao/contao/blob/c393ddfb13790de62829b40d94a425ac52b5b618/core-bundle/src/InsertTag/Resolver/LinkInsertTag.php#L38-#L117

**With fragments**

```php
#[AsInsertTag('date', asFragment: true)]
```
Code example:
https://github.com/contao/contao/blob/c393ddfb13790de62829b40d94a425ac52b5b618/core-bundle/src/InsertTag/Resolver/DateInsertTag.php#L22-#L90

**Flags**

```php
#[AsInsertTagFlag('number_format')]
```
Code example:
https://github.com/contao/contao/blob/c393ddfb13790de62829b40d94a425ac52b5b618/core-bundle/src/InsertTag/Flag/FormatFlag.php#L23-#L30

### Need more information

The PRs do explain how to use it, I wonder if there is more that I missed? /cc @ausi

**Comment by ausi** [comment]
#### Block insert tags

```php
#[AsBlockInsertTag('iflng', endTag: 'iflng')]
```

Code example: 
https://github.com/contao/contao/blob/c393ddfb13790de62829b40d94a425ac52b5b618/core-bundle/src/InsertTag/Resolver/IfLanguageInsertTag.php#L23-L25

**Comment by fritzmg** [comment]
Closing in favor of #1381
