### ISSUE TITLE
Systemvoraussetzungen Contao Manager

### ISSUE THREAD

**Issue by Mynyx** [contao/docs#139]
Die Systemvoraussetzungen zum Contao Manager (https://docs.contao.org/manual/de/installation/contao-manager/#systemvoraussetzungen) sind nur bedingt aktuell. Jedenfalls ein Hinweis, dass für die aktuelle Version mit dem vollen Funktionsumfang PHP 7.1 erforderlich ist, wäre sinnvoll.

Siehe auch https://github.com/contao/website/issues/120

**Comment by fritzmg** [comment]
@aschempp PHP 7.1 ist nicht unbedingt erforderlich, oder?

**Comment by Toflar** [comment]
Für 1.2+ schon. Die 1.1 funktioniert noch mit 5.6 aber eigentlich auch nur wegen Contao 4.4. Also der Hinweis könnte schon rein. PR wäre herzlich willkommen, @Mynyx :)

**Comment by fiedsch** [comment]
Ich frage mich, ob es sinnvoll angesichts des EOL von PHP 5.6 (https://www.php.net/supported-versions.php) sinnvoll ist, dazu noch etwas zu schrieben? Und spätestens, wenn sich die 1.1 des Managers auf 1.2 updatet ist mit schluss mit PHP 5.6. Oder habe ich da einen Denkfehler?

**Comment by Toflar** [comment]
Nein, er updated sich eben nicht. Sonst hättest du keine Möglichkeit mehr Contao zu aktualisieren ohne auf PHP 7.1 umzustellen. Er downgraded sich sogar automatisch, wenn du die 1.2 auf einem Server mit 5.6 installierst.

**Comment by fiedsch** [comment]
Ok, danke! Dann ist mein Argument hinfällig.

**Comment by netzarbeiter** [comment]
Ich habe die PHP-Version für den Manager aktualisiert.
https://docs.contao.org/manual/de/installation/contao-manager/#systemvoraussetzungen
