### ISSUE TITLE
Migrate from twigfiddle.com to twig.symfony.com/play

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#1406]
twigfiddle.com has been down for a while now. The [official statement](https://github.com/ninsuo/twigfiddle?tab=readme-ov-file#down-right-nwo) is the following:

> I need to change twigfiddle's hosting but have no time to correctly reinstall it yet.
> 
> It will be back within a couple of weeks (probably mid-june to be sure).
> 
> Your data have been backed up.
> 
> Cheers

@m-vo should we migrate to another service like https://fiddle.nette.org/twig/ or https://twig.stapps.io/ ? Do you remember the contents of the original 2 fiddles that are present in the docs?

I have added twigfiddle.com to the ignore list of the link checker for now in ac4b31e3dfd2e88e7c97ae3915277b9a05e80fa0

**Comment by m-vo** [comment]
Mhh, unfortunately I don't think I have the contents of those fiddles still lying around.

**Comment by fritzmg** [comment]
> Twigfiddle is now decommissionned and replaced by the official "twig playground" tool available at: https://twig.symfony.com/play

**Comment by fritzmg** [comment]
Ah the old links might still continue to work at some point: https://github.com/ninsuo/twigfiddle/issues/89#issuecomment-2509646091

// They already do! :)

**Comment by fritzmg** [comment]
Done via 972b5e65

**Comment by m-vo** [comment]
Nice, thanks for migrating!
