### ISSUE TITLE
link broken in hooks

### ISSUE THREAD

**Issue by zonky2** [contao/docs#141]
**Affected version(s)**
https://docs.contao.org/dev/getting-started/hook/

see below and check link at `dedicated article`

may be at this page https://docs.contao.org/dev/framework/hooks/

**Comment by fritzmg** [comment]
You don't need to create a PR and an issue. One or the other is sufficient ;).

See #140

**Comment by zonky2** [comment]
#140 !== #141

pls reopen the issue

**Comment by fritzmg** [comment]
In #140 überschreibst du genau diesen Link.
