### ISSUE TITLE
Minify HTML

### ISSUE THREAD

**Issue by fkaminski** [contao/docs#1422]
Maybe we could use [hugo minify](https://gohugo.io/hugo-pipes/minification/).

Locally (Win) I use "`--minify`" for example:
`hugo --minify server --cleanDestinationDir --environment manual --destination ../build/manual`
`hugo --minify server --cleanDestinationDir --environment dev --destination ../build/dev`

Could not find any problems so far.

**Comment by fritzmg** [comment]
Done in c38f9fa
