### ISSUE TITLE
Update XAMPP guide

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#1459]
@fkaminski I noticed that the XAMPP guide still points do a download link containing PHP 7.4.16, which is woefully outdated. Can you update it? Or may be find a link that will always point to the latest version instead.

**Comment by contaoacademy** [comment]
I think it will be best not to link to a specific version, but only to the download page. Perhaps with the note that a current PHP 8.x must be used.

- https://www.apachefriends.org/download.html
- https://sourceforge.net/projects/xampp/files/latest/download
