### ISSUE TITLE
Add backup:create cron without touching crontab

### ISSUE THREAD

**Issue by richardhj** [contao/docs#1485]
Can we add an example of how to create backups on a schedule here <https://docs.contao.org/manual/en/cli/db-backups/#have-backups-created-automatically>

**But without** the need to touch the crontab again, when the contao cron command is already in the crontab?

Unsure how to proceed here - maybe as described here <https://docs.contao.org/dev/framework/cron/#asynchronous-cron-jobs>?

**Comment by fritzmg** [comment]
You mean you want to execute other PHP commands within a Crontab?

I think the best example in this case is the [`SuperviseWorkersCron`](https://github.com/contao/contao/blob/5.x/core-bundle/src/Cron/SuperviseWorkersCron.php).

However, in case of backups you could also use the `BackupManager` directly and execute is asynchronously, yes.

Examples for both use-cases could be helpful 👍
