### ISSUE TITLE
Multiple language changes in extension section ends in a 404

### ISSUE THREAD

**Issue by MDevster** [contao/docs#166]
**Affected version(s)**
User Manual

**Description**  
Multiple language changes in extension section  ends in a 404

**How to reproduce**  
1 open https://docs.contao.org/manual/de/erweiterungen/merger2/
2 select english in language switcher
3 select german in language switcher an you get 404 not found

**Comment by fritzmg** [comment]
Thx @MDevster. Closing in favor of #169.
