### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Ernestopheles** [contao/docs#167]
**Affected version(s)**

**Description**  

**How to reproduce**  
https://docs.contao.org/manual/de/eigene-seitenlayouts/ is broken an is referenced at https://docs.contao.org/manual/de/theme-manager/seitenlayouts-verwalten/

**Comment by fritzmg** [comment]
@netzarbeiter hm, not sure where this link was actually supposed to go. Is there a page missing?

**Comment by Ernestopheles** [comment]
Well, for me it is not clear from the beginning how to create a
personal layout. Maybe it becomes more clear after solving my problem
to have a video as backgrund for the upper half part of the center-area
of a side. Just trying to build this using
http://de.contaowiki.org/Hintergrund_Video

In doing so, I faced the problem that saving a change to fe_page.html5
in /files/templates is not allowed by the Backend (403). So I changed
it by FTP. To do s.th. behind BE's back... is it ment this way?

After all The chapter layout/theme/template does not become that clear
to me from the first reading through the manual.

Am Freitag, den 15.11.2019, 02:03 -0800 schrieb Fritz Michael
Gschwantner:

**Comment by fritzmg** [comment]
> In doing so, I faced the problem that saving a change to fe_page.html5 in /files/templates is not allowed by the Backend (403). So I changed it by FTP. To do s.th. behind BE's back... is it ment this way?

Please consult the community forum for things like that ;). This is probably a security setting on your web server.
