### ISSUE TITLE
add themes section in user manual

### ISSUE THREAD

**Issue by MDevster** [contao/docs#174]
**Description**  
What do you think of adding a theme list similar to the scope of extensions?
If so, I would prepare a pull request :)

**Example**  
![Erweiterungen    Contao Handbuch](https://user-images.githubusercontent.com/10244240/68939717-8d4d3d80-07a1-11ea-9214-166bd929ccd2.png)

**Comment by netzarbeiter** [comment]
For the moment rather not.
