### ISSUE TITLE
`getContentElement` Hook parameter

### ISSUE THREAD

**Issue by Aziz-JH** [contao/docs#189]
**Affected version(s)**
Für Contao 4.8 und dessen Doku

**Description**
In der Aktuellen Doku steht unter dem [`getContentElement`](https://github.com/contao/docs/blob/master/docs/dev/reference/hooks/getContentElement.md) hook drin, dass beim dritten Parameter, nur eine `\Contao\ContentElement` Instanz zurück gegeben wird. Dies ist leider nicht immer der Fall, den wir haben auch noch das Formular, was auch darüber zurück gegeben wird und zwar als komplett eigene Instanz.

Man kann ganz gut sehen das, dass Formular in der [Contao config.php](https://github.com/contao/contao/blob/4.8/core-bundle/src/Resources/contao/config/config.php#L202), mit [`\Contao\Form`](https://github.com/contao/contao/blob/4.8/core-bundle/src/Resources/contao/forms/Form.php) nicht auf ein `\Contao\ContentElement` verweist.

Leider ein bisschen schade, dass nich auch das `\Contao\Form` als `\Contao\ContentElement` verwendet wird.

**Comment by fritzmg** [comment]
Thx :). See https://github.com/contao/docs/pull/190
