### ISSUE TITLE
Contao Manager Secret

### ISSUE THREAD

**Issue by Mynyx** [contao/docs#193]
Bei Nutzung des Contao Managers wird in ``contao-manager/users.json`` ein Secret für JSON Web Tokens (JWT) gespeichert, die zur Authentifizierung genutzt werden.

Daher sollte darauf hingewiesen werden, das Secret zu löschen (damit es automatisch neu generiert wird), wenn der Inhalt der Datei kompromittiert wurde oder beispielsweise Personen bekannt sein könnte, denen die Zugriffsberechtigung entzogen wurde.

**Comment by fritzmg** [comment]
Can you provide a PR for that?

**Comment by netzarbeiter** [comment]
Feel free to provide a PR.
