### ISSUE TITLE
Frontend Module: Service tag config via Annotations fails under Contao 4.8

### ISSUE THREAD

**Issue by markocupic** [contao/docs#210]
Service tag configuration via Annotations fails under Contao 4.8. 
What am I doing wrong?

https://github.com/markocupic/sac-event-tool-bundle/blob/800381c27ce6f4c1f1da0941b8ce7409b892b33a/src/Controller/FrontendModule/PilatusExportController.php#L44

https://github.com/markocupic/sac-event-tool-bundle/blob/800381c27ce6f4c1f1da0941b8ce7409b892b33a/src/Resources/config/controller-contao-frontend-module.yml#L121

**Comment by fritzmg** [comment]
You need to enable autoconfiguration for your service or tag it with `terminal42_service_annotation`. See https://github.com/terminal42/service-annotation-bundle/blob/master/README.md#without-autowiring-for-bundles

Also: currently you have tagged your front end module twice. Once via your YAML definition and once via annotation. You should only do one or the other.

**Comment by markocupic** [comment]
Hallo Fritz
Vielen herzlichen Dank für deine Hilfe. Ich konnte es noch nicht testen, werde es aber am Wochenende versuchen nachzuholen. 
Nice weekend.
Grüsse Marko
