### ISSUE TITLE
Service Configuration via Plugin class instead of Extension

### ISSUE THREAD

**Issue by koertho** [contao/docs#216]
On page https://docs.contao.org/dev/getting-started/extension/ / https://github.com/contao/docs/edit/master/docs/dev/getting-started/extension.md within the chapter `Service Configuration` the service loading is done by the extension class. Wouldn't it be better (and easier) to use the `ConfigPluginInterface` instead? I usually use this for service loading and it works great.

Example:
```
/**
     * Allows a plugin to load container configuration.
     */
    public function registerContainerConfiguration(LoaderInterface $loader, array $managerConfig)
    {
        $loader->load('@ContaoNamespaceBundle/Resources/config/config.yml');
        $loader->load('@ContaoNamespaceBundle/Resources/config/services.yml');
        $loader->load('@ContaoNamespaceBundle/Resources/config/listeners.yml');
    }
```

I could also do a pull request if this change should be made.

**Comment by Toflar** [comment]
Using the Manager Plugin for this use case is not correct.
Remember, whenever you're developing an extension for Contao you are essentially writing a Symfony bundle in the first place! Your bundle should be working in a regular Symfony full-stack framework application, without Contao even being present. 

If you're registering the configuration in the Manager Plugin, it **only** works for the Contao Managed Edition. This means for people that have a regular Symfony application and do not use the Managed Edition but still need some CMS functionality and added and configured the `contao/core-bundle` themselves, they won't be able to use your bundle.

The `ConfigPluginInterface` is here to configure **other** bundles within the Managed Edition. As described in the docs: https://docs.contao.org/dev/framework/manager-plugin/#the-configplugininterface

**Comment by koertho** [comment]
Ok, thanks for the explanation.
