### ISSUE TITLE
Documentation: RTE

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#22]
The DCA reference explains how to define an rte for a textarea, typically `ace` or `tinyMCE`. We should also document how to customize the editor's configuration (`be_tinyMCE.html5` template) and how to create and assign custom configurations (`be_tinyCustom.html5` - if this still actually works, I am not sure).

The editor options do not need to be documented, we can link to the documentation of tinyMCE and ACE. Only Contao-specific options should be mentioned.

**Comment by fkaminski** [comment]
I did some research - there is already a lot of information (how to create and assign custom configurations be_tinyCustom.html5) that can be summarized for the documentation. Should I put that in the guides?

**Comment by fritzmg** [comment]
Yes, having a guide is fine. We can always move it later on.

**Comment by fkaminski** [comment]
See PR #394
