### ISSUE TITLE
Contao Manager Update-Anleitungen

### ISSUE THREAD

**Issue by akroii** [contao/docs#221]
Wenn man ein Systemupgrade von z.b. 4.4 zu 4.8 machen möchte wäre es sinnvoll zu erklären wie man ein Update über das Eingabefeld fährt. Also was die einzelnen Zeichen wie `^4.4` und `.*` bedeuten.
![Bildschirmfoto 2020-01-14 um 08 51 26](https://user-images.githubusercontent.com/8830861/72324391-1ce07100-36ab-11ea-85b9-2354ebc1cdbc.png)

**Comment by Toflar** [comment]
https://getcomposer.org/doc/articles/versions.md#writing-version-constraints

**Comment by netzarbeiter** [comment]
https://docs.contao.org/manual/de/installation/contao-aktualisieren/_
