### ISSUE TITLE
document non-documented feature 'absolute' for link InsertTags

### ISSUE THREAD

**Issue by akroii** [contao/docs#238]
Theres a non-documented feature "absolute" for inserttag `{{link::234|absolute}}`. 
[https://github.com/contao/contao/blob/2aa01f5e7db13ddb9c54662dc29b17a6e998a013/core-bundle/src/Resources/contao/library/Contao/InsertTags.php#L442](https://github.com/contao/contao/blob/2aa01f5e7db13ddb9c54662dc29b17a6e998a013/core-bundle/src/Resources/contao/library/Contao/InsertTags.php#L442)

Is it possible to add this feature to user manual?

**Comment by fritzmg** [comment]
Sure, you can make a PR yourself as well by clicking the link in the documentation ;)

**Comment by fritzmg** [comment]
_Note:_ this feature is available in Contao **4.5** and up.

**Comment by akroii** [comment]
See [https://github.com/contao/docs/pull/240](https://github.com/contao/docs/pull/240)
