### ISSUE TITLE
tabs / tabbed content

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#25]
e.g.

* https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#tabs
* https://discourse.gohugo.io/t/code-tabs-widget/975/6

(https://github.com/matcornic/hugo-theme-learn/issues/70)

**Comment by fritzmg** [comment]
Preview of what's to come: https://deploy-preview-386--learn.netlify.com/en/shortcodes/tabs/

https://github.com/matcornic/hugo-theme-learn/pull/386

**Comment by Toflar** [comment]
Guess we can close this?

**Comment by fritzmg** [comment]
Yep, that has been available for some time now.
