### ISSUE TITLE
Image processing

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#255]
As discussed on Slack, the dev documentation still lacks any kind of documentation on how to utilize Contao's extensive image processing capabilities. It should go under _Framework_  > _Image Processing_. There is a lot of ground to cover, so feel free to structure it as you see fit 😉 

Things that I would definitely include:

* `ImageFactory`
* `PictureFactory`
* May be even `Controller::addImageToTemplate`? That's at least what I still often use, to add all the necessary information to a template, in order to render an image (including the meta data for example).
* The "sizes" array and all the possible resize modes, including image size IDs and strings of preconfigured image sizes (from the `config.yml`)
* Also mention deferred image resizing.
* Regarding responsive image sizes: the Contao documentation should of course not explain how `sizes`, `<picture>` etc. work, but merely explain that you can in fact set everything you need for responsive image sizes within Contao.

**Comment by ausi** [comment]
Closed in favor of #297
