### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#257]
Der Punkt _Layout_ - _Templates_ fehlt im Handbuch noch zur Gänze. Hier sollten folgende Dinge beschrieben werden:

* Anpassung von Core/Extension Templates
* Erzeugung von eigenen, auswählbaren Templates und die notwendige Namensgebung dazu
* Evt. auch Dinge wie `analytics_` Templates?

**Comment by contaoacademy** [comment]
Benennung der Templates
```
FormExplanation -> form_explanation_custom
FormHtml -> form_html_custom
FormFieldsetStart -> form_fieldsetStart_custom
FormFieldsetStop -> form_fieldsetStop_custom
FormTextField -> form_text_custom
FormPassword -> form_password_custom
FormTextArea -> form_textarea_custom
FormSelectMenu -> form_select_custom
FormRadioButton -> form_radio_custom
FormCheckBox -> form_checkbox_custom
FormFileUpload -> form_upload_custom
FormHidden -> form_hidden_custom
FormCaptcha -> form_captcha_custom
FormSubmit -> form_submit_custom
```

**Comment by zonky2** [comment]
vielleicht auch eine Anleitung, wie man über den Dev-Modus nachvollziehen kann, welches Template wo im Einsatz ist... dadurch, dass die Standardtemplates nicht mehr angezeigt werden, sicher ein wichtiger Punkt

**Comment by fritzmg** [comment]
Das würde ich in der _Templates_ Anleitung kurz erwähnen und dann auf https://docs.contao.org/manual/de/system/debug-modus/ verweisen. Dort ist das bereits dokumentiert.

**Comment by fkaminski** [comment]
See PR #386
