### ISSUE TITLE
Request Tokens

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#271]
Why and what they are for and how to retrieve them.

I'll assign this to the docs-machine 😁 (@Toflar 😉)

**Comment by Toflar** [comment]
What exactly do you imagine here and where in the docs would you expect it to appear?

**Comment by fritzmg** [comment]
_Framework_ > _Request Tokens_

1. Short explanation (i.e. required for POST request, may be link to a ressource explaining CSRF).
2. How to retrieve them + example (injecting the `contao.csrf.token_manager` service + the `contao.csrf_token_name` parameter).
3. And we still have things like the `BYPASS_TOKEN_CHECK` constant, the `disableRefererCheck` localconfig setting and the `requestTokenWhitelist` localconfig setting in the legacy `RequestToken` class - which is deprecated, but still used by the core.

**Comment by Toflar** [comment]
Done :)
