### ISSUE TITLE
update-contao.de.md Abschnitt Aktualisierung mit dem Contao Manager

### ISSUE THREAD

**Issue by Mynyx** [contao/docs#275]
Im Abschnitt "Aktualisierung mit dem Contao Manager" (https://docs.contao.org/manual/de/installation/contao-aktualisieren/#aktualisierung-mit-dem-contao-manager) wird der Ablauf folgendermaßen beschrieben:
> Bei einer Aktualisierung für ein Minor-Release klicke bei »Contao Open Source CMS« auf das Zahnrad-Symbol und gebe die gewünschte Version ein. Alle anderen Contao-Paketen müssen ohne Änderung für die Aktualisierung vorgemerkt werden. Durch einen Klick auf die Schaltfläche »Änderungen anwenden« schiebst du die Aktualisierung an.

Was genau ist mit dem Satz "Alle anderen Contao-Paketen müssen ohne Änderung für die Aktualisierung vorgemerkt werden." gemeint? Was konkret soll an dieser Stelle getan werden?

**Comment by fritzmg** [comment]
Den Button "Aktualisieren" klicken.

**Comment by Mynyx** [comment]
Der Button "Aktualisieren" bei den Contao-Paketen ist nach dem Ändern der Version ausgegraut. Auch der allgemeine Button "Pakete aktualisieren" ist nach dem Ändern der Version ausgegraut.

Bezieht sich der Satz vielleicht noch auf eine ältere Version des Contao Managers, wo die Contao-Pakete noch nicht gruppiert waren?

Oder sind mit Contao-Pakete auch die Erweiterungen gemeint?

**Comment by fritzmg** [comment]
> Bezieht sich der Satz vielleicht noch auf eine ältere Version des Contao Managers, wo die Contao-Pakete noch nicht gruppiert waren?

Ja, bezieht sich grundsätzlich noch darauf. Je nach dem welche Erweiterungen installiert sind, kann es aber trotzdem notwendig sein, auch alle anderen Pakete zur Aktualisierung zu markieren. Oder man führt unter _Wartung_ > _Abhängigkeiten installieren_ ein komplettes composer update durch (nachdem man die Version geändert hat).

**Comment by netzarbeiter** [comment]
Der Text wurde angepasst.
