### ISSUE TITLE
Update Symfony Application configuration for Contao 4.9

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#300]
@sheeep could you please provide PR to update https://docs.contao.org/dev/getting-started/starting-development/ to include the necessary changes for Contao 4.9? :)

May be split it between Contao 4.4 or 4.9? Both should stay imho.

**Comment by bytehead** [comment]
You mean over here: https://docs.contao.org/dev/getting-started/initial-setup/symfony-application/?

**Comment by fritzmg** [comment]
Right sorry, copied the wrong link.

**Comment by bytehead** [comment]
Can you assign the issue to me then?

**Comment by fritzmg** [comment]
Done.

**Comment by bytehead** [comment]
@fritzmg this issue can be closed.
