### ISSUE TITLE
example config.yml is not valid

### ISSUE THREAD

**Issue by Xendiadyon** [contao/docs#308]
In https://docs.contao.org/manual/de/system/einstellungen/ there is the default config.yml.

But when I store this code in the config/config.yml and rebuild the cache, I get the error:

```
  The file "/www/htdocs/w00e1aee/dev/config/config.yml" does not contain valid YAML: You cannot define a mapping item when in a sequence at line 19 (near "prepend_locale:       false")
```

So the example config.yml doesn't seem to be correct.

---

When I try to output the default configuration via
`php vendor/bin/contao-console config:dump-reference contao`
I get the error:
```
18:36:24 ERROR     [console] Error thrown while running command "config:dump-reference contao". Message: "Impossible to call set() on a frozen ParameterBag." ["exception" => Symfony\Component\DependencyInjection\Exception\LogicException
```

So this line does not work either, without any help/information :(

System:
Contao 4.9.1 LTS Managed Edition 
PHP 7.4.2 (cli)

**Comment by chuckki** [comment]
Hi - the document shows the reference, not a workable configuration. Maybe the following wording is ponderously: 
'Über die Kommandozeile kommst du an die Standard-Konfiguration für Contao:'

For the current configuration use: `php vendor/bin/contao-console debug:config contao`

**Comment by fritzmg** [comment]
@Xendiadyon what exactly are you trying to do?

**Comment by netzarbeiter** [comment]
No problem in Contao 4.9.3, I have added the line from @chuckki.
https://docs.contao.org/manual/de/system/einstellungen/

**Comment by Xendiadyon** [comment]
Sorry for not answering sooner. I will switch on mail notifications for GitHub.

After upgrading to Contao 4.9.3, I still get the error
```
14:55:50 ERROR     [console] Error thrown while running command "config:dump-reference contao". Message: "Impossible to call set() on a frozen ParameterBag." ["exception" => Symfony\Component\DependencyInjection\Exception\LogicException
```

regardless if I try
` php vendor/bin/contao-console config:dump-reference contao`
or
`php vendor/bin/contao-console debug:config contao`



@fritzmg I am trying to get a default (working) config.yml which I can edit further.

**Comment by fritzmg** [comment]
> @fritzmg I am trying to get a default (working) config.yml which I can edit further.

You should simply only add the things you need, not copy the whole reference dump into your own `config.yml`.

Regarding the error you are experiencing: you should ask in the community for help (Slack or Forum).
