### ISSUE TITLE
Document ContaoModuleBundle

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#310]
If you install packages of type `contao-module` in your Symfony application, you will need to use the `ContaoModuleBundle` class in order to load these extensions in the application.

@bytehead can you add an article about that to the Symfony Application setup documentation? :)

**Comment by bytehead** [comment]
👍

**Comment by fritzmg** [comment]
Btw. @ausi suggested [here](https://github.com/contao/contao/issues/216#issuecomment-447897985) that one could may be reuse `ContaoKernel::registerBundles` to automatically load any `contao-module` packages?

**Comment by bytehead** [comment]
Should it also be possible to define the environments the modules gets loaded, like e.g.:
```php
return [
    'easy_themes' => ['all' => true],
];
```

or should the system always load `contao-module` packages?

**Comment by fritzmg** [comment]
I have no idea 😁

**Comment by bytehead** [comment]
Loading them in every environment will be automatically possible without manually adding the module somewhere after a `composer require`...

**Comment by bytehead** [comment]
This can be closed.
