### ISSUE TITLE
Clarify how often the package search index runs

### ISSUE THREAD

**Issue by amenk** [contao/docs#329]
> If your package is of "type": "contao-bundle" and is published to packagist.org, our search index will > automatically pick it up.

In https://github.com/contao/docs/blob/master/docs/dev/guides/publishing-bundles.md L75 it's not specified how often the search index runs. That is important. Can somebody who knows add it?

Thank you :)

**Comment by fritzmg** [comment]
@aschempp should we add that to the documentation?

**Comment by aschempp** [comment]
We‘ve put the index updates on GitHub Actions so its visible to everyone: https://github.com/contao/package-metadata/actions

Currently, there‘s an update every 30 minutes, plus an instant one if something is added to the metadata repository. 

_If_ we want to add something to the docs, I‘d link to the Actions and not write down „30mins“ as that could change.

**Comment by fritzmg** [comment]
@amenk feel free to make a PR for the docs :)

**Comment by amenk** [comment]
Cool -- PR done.

So I have another problem (https://community.contao.org/de/showthread.php?77637-Wieso-erscheint-unser-Paket-nicht-im-Contao-Manager&p=523069#post523069)

**Comment by amenk** [comment]
#330
