### ISSUE TITLE
Falsches Service-Tag für Cron Jobs

### ISSUE THREAD

**Issue by jdwiese** [contao/docs#346]
Das Service-Tag für Cron-Jobs heißt "contao.cronjob" und nicht wie in der Dokumentation angegeben "contao.cron" (https://docs.contao.org/dev/framework/cron/). Das wird auch in der Deprecation-Meldung so angegeben:

```"User Deprecated: Using $GLOBALS['TL_CRON'] has been deprecated and will be removed in Contao 5.0. Use the "contao.cronjob" service tag instead."```

**Comment by fritzmg** [comment]
fixed in 41e8059

Übrigens @jdwiese rechts oben kannst du die Seite selbst editieren und Änderungen vorschlagen ;)
