### ISSUE TITLE
Mumble Anleitung ins Handbuch übernehmen

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#350]
Aus dem alten Wiki.

**Comment by contaoacademy** [comment]
https://de.contaowiki.org/Mumble_Installation

**Comment by frontendschlampe** [comment]
unter dem Menüpunkt "Anleitungen"

**Comment by fkaminski** [comment]
See PR #400
I only took the texts and photos from the wiki without installing them myself. So perhaps these are not uptodate...
