### ISSUE TITLE
Add Simple Tokens to manual

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#354]
Stuff like

```
{if foo=='foo'}…
```

is currently not documented at all (I think?). We should add it to the _Insert-Tag_ documentation imho. It's not really the same, but conceptually it would fit there best, I think.

**Comment by Tastaturberuf** [comment]
But it only works on the newsletter module? 

> Simple Tokens ist womöglich eines der meistunterschätzten Features innerhalb von Contao und wird im Kern von Contao leider auch nur für das Newsletter-Modul verwendet.

source: 
https://isotopeecommerce.org/de/handbuch/v/2.6/r/simple-tokens.html#deeplink-simple-tokens

**Comment by zonky2** [comment]
hmm...

I would rather do this as an extra page in module management - similar to insert tags in article management.
https://docs.contao.org/manual/de/modulverwaltung/

With the modules concerned then a link to the page.

**Comment by fritzmg** [comment]
> But it only works on the newsletter module?

It works wherever `StringUtil::parseSimpleTokens` is used. Within the core bundles that's:

* `ModulePassword`
* `Newsletter`
* `ModuleNewsletterReader`
* `ModuleSubscribe`
* `ModuleUnsubscribe`

Plus any extension that utilises it (e.g. `terminal42/notification_center`).

**Comment by zonky2** [comment]
since this is more applicable in the modules section, I would add this to the modules section.

In the NC, you can then create a link in the documentation to the page ;-)

**Comment by netzarbeiter** [comment]
The entry was extended some time ago, can I close this ticket?

https://docs.contao.org/manual/de/core-erweiterung/newsletter/newsletter-verwaltung/#newsletter-personalisieren

**Comment by zonky2** [comment]
I think with the new possibilities that @Toflar has built in, you could make a page out of it.

**Comment by netzarbeiter** [comment]
https://github.com/contao/docs/pull/1035
