### ISSUE TITLE
parameters.yaml: install Passwort?

### ISSUE THREAD

**Issue by math-GH** [contao/docs#358]
![grafik](https://user-images.githubusercontent.com/1645099/81474491-0d5ed800-9206-11ea-8efc-b1fcc838bbe7.png)
https://docs.contao.org/manual/de/system/einstellungen/

aber das Install-Passwort befindet sich aktuell in system/config/localconfig.php
![grafik](https://user-images.githubusercontent.com/1645099/81474498-2bc4d380-9206-11ea-8a11-01980ee5e2ed.png)
https://contao.org/de/faq/ich-habe-das-passwort-fuer-das-installtool-vergessen.html

Ich denke, dass der Hinweis auf das Install-Passwort weg sollte oder spezifiziert werden sollte, wann es dort steht. Bei mir steht es (Contao 4.9.2) nicht in parameters.yaml

**Comment by contaoacademy** [comment]
Du kannst die Daten vom Install-Tool auch in der parameters.yml eintragen. 

```
contao:
    localconfig:          ~
```

**Comment by math-GH** [comment]
> 
> 
> Du kannst die Daten vom Install-Tool auch in der parameters.yml eintragen.
> 
> ```
> contao:
>     localconfig:          ~
> ```

gibt es dazu eine Doku, wann und wie das Passwort dort reinkommt?

2016 war noch die Aussage:
![grafik](https://user-images.githubusercontent.com/1645099/81484359-25a21780-9245-11ea-9838-5f6f98c52e9e.png)
https://github.com/contao/installation-bundle/issues/27
(sag niemals nie? ;) )

**Comment by fritzmg** [comment]
Die `config.yml` editierst du grundsätzlich selbst.

**Comment by math-GH** [comment]
> 
> 
> Die `config.yml` editierst du grundsätzlich selbst.

aktuell reden wir über die parameters.yaml, oder? ;)

**Comment by fritzmg** [comment]
Nein, das Install Tool Passwort wird in der localconfig.php definiert. Die schon erwähnt kannst du die `TL_CONFIG` Werte auch in der Konfiguration des Contao Core Bundles definieren (also in der `config/config.yml`).

**Comment by math-GH** [comment]
wieso reden wir über die confi.yaml, wenn ich die ganze Zeit die parameter.yaml meine und sie oben im Screenshot zu sehen ist. Die config.yaml kommt in der Doku im nächsten Abschnitt.

In der Doku steht, dass das Install-Passwort in der parameters.yaml enthalten sein kann.
Bis jetzt konnte diese Aussage hier im Gespräch nicht bestätigt werden.
Also gehe ich davon aus, dass die Doku nicht korrekt ist.
Deshalb dieses Issue.

**Comment by fritzmg** [comment]
Danke, habe das nun entfernt :)
