### ISSUE TITLE
Disable the security question -> Disable spam protection

### ISSUE THREAD

**Issue by leofeyer** [contao/docs#359]
As suggested in contao/contao#1718, we are renaming the "Disable the security question" option to "Disable spam protection" in contao/contao#1740. We might have to adjust this in the docs as well.

**Comment by fritzmg** [comment]
PR: #364 

While working on this I noticed, that the form field in the form generator is still called "Security question", even though it's also just an invisible spam protection (see https://github.com/contao/contao/pull/1740#issuecomment-629646406).

**Comment by leofeyer** [comment]
Our spam protection consists of two things: An invisible honeypot field and a visible security question that is shown if the honeypot field is filled in. Therefore "security question" is the correct label for the security question. 😄

**Comment by netzarbeiter** [comment]
https://github.com/contao/docs/pull/364
