### ISSUE TITLE
Contao Image Processing

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#36]
Damit meine ich jetzt nicht die Erklärung der Responsive Image Funktion etc. (die gehört natürlich auch in das Handbuch) sondern ich finde man sollte im Handbuch ein wenig auf die unterstützten Image Libraries und deren Unterschiede eingehen. Also GD, Imagick & Gmagick. Unterschiede & Vorteile. Und wie man im Zweifelfall per Konsole überprüfen kann, was nun von Contao tatsächlich automatisch verwendet wird (via `debug:container`).

**Comment by netzarbeiter** [comment]
https://docs.contao.org/manual/de/installation/systemvoraussetzungen/#php-erweiterungen
