### ISSUE TITLE
Documentation: Annotations

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#41]
* [x] hooks
* [x] DCA callbacks
* [x] content element & front end module controllers

**Comment by fritzmg** [comment]
Hm, warum haben wir eigentlich eine eigene Service Annotation für Hooks - aber nicht für alles andere? Die Hooks könnte man ja eigentlich auch mit dem Service Annotation Bundle setzen.

**Comment by aschempp** [comment]
`terminal42/service-annotation-bundle` ist die Grundlage. Wir haben Kindklassen für einige unserer Tags, damit diese einfacher zu erstellen sind. Es gibt mehr als Hooks, es gibt auch Fragments und Callbacks.
