### ISSUE TITLE
Manual: step-by-step guide

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#43]
@netzarbeiter darüber haben wir ja schon mal geredet - also dass es Sinn machen würde eine Art Step-by-Step guide in das Handbuch zu integrieren, wo man durch das Grundsetup von Contao geführt wird, da das bisher eigentlich noch nirgends so erklärt war. Neuankömmlinge in Contao wissen oft nicht, dass zumindest folgende Schritte notwendig sind, um erste Inhalte auf seiner Contao Webseite sehen zu können:

1. Theme anlegen
2. Seitenlayout im Theme anlegen
3. Webseiten Startpunkt anlegen
4. Seitenlayout im Webseiten Startpunkt auswählen
5. Startseite mit Alias `index` anlegen
6. Startseite mit Inhalt befüllen

Siehe dazu auch https://github.com/contao/contao/issues/601

**Comment by fkaminski** [comment]
Hi, kann mich gerne daran beteiligen. Wie stellst Du Dir die entsprechende (hugo) file struktur vor bzw. wo sollte das in der Navi auftauchen Position/Name ...

**Comment by fkaminski** [comment]
Hi, ich kann morgen mal mit dem Bereich "Guides/Anleitungen" anfangen.

Wie wäre es, wenn wir die Beschreibungen für "Lokale Installationen" (s. PR #99)  auch in den Bereich "Guides/Anleitungen" verschieben?

Platz wäre in der Navi, und so hätten wir eine saubere Trennung.

**Comment by fkaminski** [comment]
@fritzmg Könnte man schließen ...

**Comment by fritzmg** [comment]
Gibt es diese Anleitung nun schon?

**Comment by fkaminski** [comment]
Dachte diese hier:
https://docs.contao.org/manual/de/anleitungen/die-erste-startseite/

**Comment by netzarbeiter** [comment]
Vielleicht müssen wir den Titel «Die erste Startseite» in «Erste Inhalte auf der Website ausgeben» ändern, dass klarer wird um was es sich bei dieser Anleitung handelt?

**Comment by fritzmg** [comment]
Ja, oder einfach nur "Die ersten Inhalte", damit der Titel nicht so lang ist und besser in das Menü passt :)

**Comment by netzarbeiter** [comment]
Er müsste in meinen Augen schon etwas ausssagekräftiger sein.

**Comment by fkaminski** [comment]
Ich finde "Die ersten Inhalte" auch passend. Zumal es von der Länge her wirklich besser in die Doku-Navi passt.

**Comment by netzarbeiter** [comment]
… sagt halt nicht aus.

Die ersten Inhalte …

- Erste Inhalte einpflegen
- Erste Seite veröffentlichen
- Erster Inhalt ausgeben

**Comment by fkaminski** [comment]
In diesem Fall ist es eh ja "nur" unter den Guides aufgeführt. Für den TOC reicht es ja dann aus.
Man könnte zusätzlich an den passenden Stellen dann mit ausssagekräftigen Titeln verlinken:
z.B hier dann auf der index Seite des "Theme-Manager" ...

**Comment by fkaminski** [comment]
Im PR #404 habe ich u. a. mal Cross-Link (auf die guides) in der Index-Seite des Bereichs Layout/Theme-Manager gesetzt

**Comment by fkaminski** [comment]
Da PR #404 gemergt wurde könnte man dies schließen, sofern der Umweg über Cross-Links eine temporäre Lösung ist...
