### ISSUE TITLE
Change name of variable in example of picture factory

### ISSUE THREAD

**Issue by zonky2** [contao/docs#484]
https://docs.contao.org/dev/framework/image-processing/image-picture-factory/#example

the first and second example has as varaible `$image` - the third example `$resizedImage` ...

To avoid misunderstandings it might be better to name the variable in all three examples the same as `$image` or `$resizedImage`

**Comment by fritzmg** [comment]
In the top right corner of the documentation is a link called _Edit this page_, with which you can quickly make a PR for such small fixes and suggestions :)

**Comment by zonky2** [comment]
For changes where I am quite sure, I do this as you know - here I was not sure if there is a special reason...

https://github.com/contao/docs/pull/485

**Comment by fritzmg** [comment]
> here I was not sure if there is a special reason...

We'll find out in the PR ;). Closing in favor of #485
