### ISSUE TITLE
Cookbook: add custom CSS to the back end

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#50]

**Comment by fritzmg** [comment]
@Toflar @aschempp I'd need some help here. As mentioned [here](https://github.com/contao/contao/issues/446#issuecomment-529368654) I am trying to figure out what the best practice is now for adding additional (global) assets in the back end.

Previously people used the `TL_MODE` check within `config.php` which is considered wrong, since the `config.php` should only include config, not logic. (However the core still does it too, as mentioned in the Contao issue!)

**Comment by aschempp** [comment]
I don't think there's a "perfect" way to do this. There are multiple ways I can think of:
 - a `kernel.request` listener and check the back end scope
 - a `parseTemplate` hook and check for the `be_main` template
 - any other hook or event that is always triggered in the back end. `initializeSystem` would work but pretty stupid I guess.

It always boils down to `$GLOBALS['TL_MOOTOOLS']` I guess, which is just 🤮
