### ISSUE TITLE
prev/next navigation is broken

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#52]
Leider funktionieren die prev/next Links nicht richtig: https://github.com/matcornic/hugo-theme-learn/issues/163

**Comment by bonartm** [comment]
I have experienced the same issues of skipped sections during navigation.

I made a small change in `layouts/partials/footer.html` and it  solved the navigation issues for my projects (see https://github.com/bonartm/hugo-theme-learn/commit/2583aaab832e7ef36bb9e625845f34c4c5b44220).

But I know too little of Hugo's internals so I cannot fully explain why this works and if it works in all cases with no side effects.

**Comment by fritzmg** [comment]
Fixed via #176
