### ISSUE TITLE
Docs Initial Setup Contao 4.9 LTS 

### ISSUE THREAD

**Issue by ghost** [contao/docs#527]
Hello! 

I worked my way through the instructions here:
https://docs.contao.org/dev/getting-started/initial-setup/symfony-application/contao-4.9/

The following errors have been found:

$ composer require \
    doctrine/dbal:^2.10 \
    doctrine/doctrine-bundle ^1.8 \<---------------------------- should mean: doctrine/doctrine-bundle:^1.8
    doctrine/migrations:^2.2 \        <---------------------------- should mean: doctrine/migrations:^3.0.1 (should be >= 3.0.0) 
    contao/conflicts:@dev \
    contao/core-bundle:4.9.* \
    contao/installation-bundle:4.9.* \
    php-http/guzzle6-adapter \
    toflar/psr6-symfony-http-cache-store \
    twig/twig ^2.7

inconsistent path information

config/doctrine.yml > config/packages/doctrine.yml
config/translation.yml > config/packages/translation.yml
config/framework.yml > config/packages/framework.yml
config/security.yml > config/packages/security.yml

Compile Error: App\HttpKernel\AppKernel::registerBundles(): Failed opening required '/var/www/contao/src/config/bundles.php' (include_path='.:/usr/share/php')

// ok. i can solve that..

and then 
You have requested a non-existent service "security.authentication.manager".

I don't get any further with that. :(

it would be very nice if someone could revise the documentation, especially with regard to the error with the non-configured service. I am open to your questions and suggestions. 

many greetings, Anja

**Comment by bytehead** [comment]
I've updated the docs, but cannot reproduce the issue with the non-existent service. 
@anniahoi did you configure `config/packages/security.yaml` properly?

**Comment by olifrieda** [comment]
Currently docs for initial setup 4.9 does not work. Here is a list of some issues. After the Symfony skeleton has been installed successfully:
```
$ composer require contao/conflicts:@dev contao/core-bundle:4.9.* contao/installation-bundle:4.9.* php-http/guzzle6-adapter toflar/psr6-symfony-http-cache-store twig/twig:^2.7
zsh: no matches found: contao/core-bundle:4.9.*
```
Ok, try again without version:
```
$ composer require contao/conflicts:@dev contao/core-bundle contao/installation-bundle php-http/guzzle6-adapter toflar/psr6-symfony-http-cache-store twig/twig
Using version ^4.11 for contao/core-bundle
Using version ^4.11 for contao/installation-bundle
Using version ^2.0 for php-http/guzzle6-adapter
Using version ^3.0 for toflar/psr6-symfony-http-cache-store
Using version ^3.3 for twig/twig
./composer.json has been updated
Running composer update contao/conflicts contao/core-bundle contao/installation-bundle php-http/guzzle6-adapter toflar/psr6-symfony-http-cache-store twig/twig
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "4.4.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - contao/core-bundle[4.11.0, ..., 4.11.2] require twig/twig ^2.7 -> found twig/twig[v2.7.0, ..., v2.14.4] but it conflicts with your root composer.json require (^3.3).
    - Root composer.json requires contao/core-bundle ^4.11 -> satisfiable by contao/core-bundle[4.11.0, 4.11.1, 4.11.2].
```
Nice! Installed Contao 4.11 but with some problems. So let's change the composer.json
```
       "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0"
```
into
```
       "twig/extra-bundle": "^2.12",
        "twig/twig": "^2.12"
```
Removed the composer.lock and vendor folder and run `composer update`. Now the packages were installed, but auto configuration failed:
```
  - Configuring contao/installation-bundle (>=4.6): From github.com/symfony/recipes-contrib:master
...
!!  In Kernel.php line 291:
!!                                                                                 
!!    Unable to find file "@ContaoInstallationBundle/Resources/config/routing.yml  
!!    ".                                                                           
!!                                                                                 
```
Yes, the file doesn't exist. Maybe it has been renamed to `routes.yml`
Edit `config/routes/contao_installation.yaml`:
```
contao_installation:
    resource: "@ContaoInstallationBundle/Resources/config/routes.yml"
```
Now this works. Let's start the configuration process: add routes
```
ContaoInstallationBundle:
    resource: "@ContaoInstallationBundle/Resources/config/routing.yml"

ContaoCoreBundle:
    resource: "@ContaoCoreBundle/Resources/config/routing.yml"
```
Doesn't look good. `ContaoInstallationBundle` has been configured by auto configuration => no need to add again. `ContaoCoreBundle` => it is not the `routing.yml` but `routes.yml`

So far, so good. The rest has been configured like written in the description. We'll start the install process in the web browser!

Everything worked except the database update:
```
CREATE INDEX name ON tl_cron_job (name)

An exception occurred while executing 'CREATE INDEX name ON tl_cron_job (name)':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
```
Tested with mysql 5.7.32 (encoding utf8mb4 / utf8mb4_bin)
PHP7.4.12
composer 2.0.12

**Comment by fritzmg** [comment]
> Everything worked except the database update:

If this issue still occurs, please report that in https://github.com/contao/contao/issues
