### ISSUE TITLE
Manage image sizes

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#551]
As mentioned [here](https://github.com/contao/docs/pull/534/files#r477135704) it would be great to have a dedicated article for "Manage image sizes" within https://docs.contao.org/manual/en/layout/theme-manager/ (just as "Manage stylesheets" and "Manage page layouts"), explaining all the possibilities (but not go into detail about how why and when to use responsive images etc. - we should link to other articles for that), including the possibility to define image sizes in the `config.yml`.

**Comment by netzarbeiter** [comment]
https://github.com/contao/docs/issues/643
