### ISSUE TITLE
Update contao locally

### ISSUE THREAD

**Issue by netzarbeiter** [contao/docs#575]
Explain how Contao can be updated locally without the Composer Resolver Cloud.

**Comment by fiedsch** [comment]
This is what I am doing to update my sites where memory is short and I do not want to use cloud resolver resources for no reason. So if I can help by describing the process or supply code examples: let me know!

**Comment by netzarbeiter** [comment]
It would be great if you could write this post, then we could refer to it in the discussion board in case of problems. May I assign this issue to you?

**Comment by fiedsch** [comment]
Yes.

I certainly will need your help in some aspects. To start with: where would I put that within the documentation structure? I would start to write the german part and the translate to english, once that is published. Correct?

**Comment by fritzmg** [comment]
> I would start to write the german part and the translate to english, once that is published. Correct?

Ideally we will add the English translation directly to your PR, before it is merged, so that English and German stays consistent

**Comment by netzarbeiter** [comment]
I would put it either [here](https://docs.contao.org/manual/de/installation/contao-aktualisieren/) or as a separate point directly below.
