### ISSUE TITLE
Guide - Examples with the module "Auflistung"

### ISSUE THREAD

**Issue by fkaminski** [contao/docs#582]
Some practical examples of the "Auflistung" module.
Please asig to myself

**Comment by fkaminski** [comment]
Wie mit @netzarbeiter auf Slack vereinbart mit folgender Beispiel-Anwendung (basierend auf Contao Bordmitteln):

- Listen Darstellung von Mitgliedern zusammen mit einer Karten Anzeige entsprechender Mitglieder via 
(Openstreetmap / leaflet) - optional mit Cluster Anzeige (https://github.com/Leaflet/Leaflet.markercluster)

Bezüglich des Geo-Codings wollte ich drei Möglichkeiten vorstellen:

1. Via manueller Koordinaten Eingabe (Neues Feld über contao/dca/tl_member.php)
2. Eine Nominatim Search Abfrage selbst implementieren (Neues Feld über contao/dca/tl_member.php)
3. Optional: Die Erweiterung https://github.com/netzmacht/contao-leaflet-geocode-widget in (contao/dca/tl_member.php) einbinden/nutzen

Zu 2.) benötige ich Hilfe bez. der DCA Konfiguration. 
Möchte ein Text Feld (Koordinaten) zur manuellen Eingabe erstellen. Daneben soll eine Schaltfläche/Icon angezeigt werden zwecks Aufruf einer eigenen Methode. Das Ergebnis der Methode soll dann wieder im Textfeld eingetragen werden. Könnte mir jemand dazu das Gerüst/Struktur (für die contao/dca/tl_member.php) als Beispiel geben (Komme mit eigenen Versuchen hinsichtlich wizard und callback Angaben diesbezüglich nicht weiter)? 
Also nur das Gerüst - das Geo-Searching Sample bekomme ich hoffentlich hin :-) )
Danke

**Comment by fkaminski** [comment]
Maybe @fritzmg could help with this?
See also https://community.contao.org/de/showthread.php?79207-DCA-tl_member-Manipulation ...
(Sorry for pushing)
Otherwise I would limit - at first - to examples with manual specification and use of the widget extension (see above) regarding the auto geo search ...

**Comment by fritzmg** [comment]
That seems pretty advanced for a listing-bundle guide. Especially if you want to build your own back end widget - that would be its own guide for the dev docs ;). Instead of building your own widget, I would simply do it with a `save_callback` on the coordinates text field. But still, I think that is way out of scope for a listing-bundle guide.

**Comment by fkaminski** [comment]
Thank you.
Since I am describing how to create another member field anyway, I thought it would be a useful addition. But I wanted to be able to trigger it somehow optional and not generally when saving. 
Let's see, I will first implement it as discussed ...

**Comment by fritzmg** [comment]
Well you could add a checkbox "Update geo information on save". But still, do you really want to add it to such a guide? Imho this has nothing to do with how to use the listing-bundle.

**Comment by fkaminski** [comment]
> Well you could add a checkbox "Update geo information on save". But still, do you really want to add it to such a guide? Imho this has nothing to do with how to use the listing-bundle.

Will try. Maybe you are right and it could be explained in more detail later in a new guide ...

**Comment by fritzmg** [comment]
> Maybe you are right and it could be explained in more detail later in a new guide ...

In the dev docs ;)

**Comment by fkaminski** [comment]
Closing if you do not mind because of #611
