### ISSUE TITLE
Document how to use MySQL / MariaDB UDS instead of TCP in parameters.yml

### ISSUE THREAD

**Issue by GottZ** [contao/docs#584]
Today i noticed, you can omit `database_host` and `database_port` inside `parameters.yml` to let Doctrine use `/run/mysqld/mysqld.sock`, or what ever is configured in php.ini's mysqli section, instead.

https://github.com/doctrine/dbal/blob/16878650d79934c31e27a13618ed6f3effee80d8/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php#L67

I assume it would be great to either add `database_unix_socket` and / or `database_dca` to `parameters.yml` in future Contao Versions, as well as document that this Fallback can be used to gain access to the default or php.ini configured UDS.

This Documentation would have saved me quite some Time today.

**Comment by fritzmg** [comment]
Do you mean

```yaml
# config/config.yaml
doctrine:
    dbal:
        unix_socket: ...
```

? This is documented here: https://symfony.com/doc/current/reference/configuration/doctrine.html

I suppose the manual could reference this somewhere in a section for more advanced configurations.

**Comment by fritzmg** [comment]
@GottZ still would need confirmation that that is what you meant.

**Comment by GottZ** [comment]
four years have passed. Yes you are right on this one.
