### ISSUE TITLE
contao-console Commands cache:clear and cache:warmup

### ISSUE THREAD

**Issue by fkaminski** [contao/docs#589]
Is it possible that the following console commands (Managed Edition) are not mentioned anywhere?

- vendor/bin/contao-console cache:clear --no-warmup
- vendor/bin/contao-console cache:warmup

https://docs.contao.org/dev/reference/commands/

**Comment by fritzmg** [comment]
The documentation currently only mentions contao specific commands. Unfortunately there is no documentation on all the available symfony commands. However, you can list all commands with `list` and for each command you can get more information with `--help`. We could add that information to the reference.

**Comment by fkaminski** [comment]
reopened ??? What can i do?

**Comment by fritzmg** [comment]
I reopened it as a reminder to myself: 

> However, you can list all commands with `list` and for each command you can get more information with `--help`. **We could add that information to the reference.**

**Comment by fkaminski** [comment]
Could possibly closed? See: https://docs.contao.org/dev/reference/commands/

**Comment by fritzmg** [comment]
I suppose, yes :)
