### ISSUE TITLE
DCA manipulation helpwizard / explanation / explain.php

### ISSUE THREAD

**Issue by fkaminski** [contao/docs#592]
Perhaps an example of this constellation would be helpful.
So own, multilingual, help texts via helpwizard/explanation and separate contao/languages/de/explain.php / contao/languages/en/explain.php files via

```
// contao/languages/de/explain.php
$GLOBALS['TL_LANG']['XPL']['my_explanation'] = array
(
    array
    (
        'colspan', '<h2>Hilfetext AAA</h2>kommt noch <br> hier ...'
    )
); 
```

**Comment by fritzmg** [comment]
See #605
