### ISSUE TITLE
Update »Datenbanktabellen aktualisieren« via Konsole

### ISSUE THREAD

**Issue by fkaminski** [contao/docs#594]
In https://docs.contao.org/manual/de/installation/contao-installieren/#datenbanktabellen-aktualisieren-1
wird die Datenbanktabellen Erstellung/Aktualisierung über:

`vendor/bin/contao-console contao:migrate`

erwähnt/vorgestellt. 
Evtl. wären hier weitere Angaben bez. der notwendigen Konfigurations Voraussetzungen über die `.env ` bzw. `config/parameters.yml ` hilfreich (wie heute auf Slack besprochen). Wenn auch nur mit Links zu:

- https://docs.contao.org/dev/getting-started/starting-development/
- https://docs.contao.org/dev/reference/config/#database-url
- https://docs.contao.org/dev/reference/config/#app-secret

**Comment by fkaminski** [comment]
Maybe with a hint in https://docs.contao.org/dev/reference/commands/#contao-migrate too...
(Currently it reads as if this could only be used for updates)

**Comment by fritzmg** [comment]
> Currently it reads as if this could only be used for updates

It can be used for migrating the database, no matter if it is a fresh installation, or an update. Why would it only able to be used for updates? Or what do you mean by "updates"?

> Evtl. wären hier weitere Angaben bez. der notwendigen Konfigurations Voraussetzungen über die `.env ` bzw. `config/parameters.yml ` hilfreich (wie heute auf Slack besprochen). Wenn auch nur mit Links zu:

Can you provide a PR? ;) You just have to mention that the database credentials need to be defined first, no matter which way.

**Comment by fkaminski** [comment]
> > Currently it reads as if this could only be used for updates
> 
> It can be used for migrating the database, no matter if it is a fresh installation, or an update. Why would it only able to be used for updates? Or what do you mean by "updates"?

Now i know too. But:
> With this command you can execute migrations after an update of Contao or of an extension.

could be translated with:

> Mit diesem Befehl können Sie Migrationen nach einem Update von Contao oder einer Erweiterung durchführen.

So - maybe it could be misunderstood ...

I will ry to describe it - Please asign to myself

**Comment by fritzmg** [comment]
Ah, I see what you mean now. Yeah, the description should be more general.
