### ISSUE TITLE
Guide: Using CSS Animation within Contao

### ISSUE THREAD

**Issue by fkaminski** [contao/docs#606]
A few practical examples for using and integrating CSS animations.
Maybe with examples like:

- https://github.com/animate-css/animate.css?files=1
- https://wowjs.uk/
- http://imakewebthings.com/waypoints/

Please assign to myself ...

**Comment by zonky2** [comment]
extension for wowjs: https://github.com/inspiredminds/contao-wowjs

**Comment by fkaminski** [comment]
I am in the process of writing the content. The main plan was a description of CSS animations (no pure SVG animations). Then in combination with wow.js or waypoint.js within Contao.  

Another option would be a description of the implementation/sample of using [Lottie](https://lottiefiles.com/) files (.json + .js player) within Contao.

Should I include this in a single file or split it into two PR's ...?

**Comment by fkaminski** [comment]
My Reminder: 
Because of https://www.delac.io/WOW/#pricing
Alternative: https://github.com/aljs/wew.js with [MIT License](https://github.com/aljs/wew.js/blob/master/LICENSE.md)

**Comment by fkaminski** [comment]
Contributions for the manual should be Contao specific. 
This topic would be more general. I am therefore closing this.
