### ISSUE TITLE
Guide: First Navigation (desktop and mobil)

### ISSUE THREAD

**Issue by fkaminski** [contao/docs#607]
As a further complement to:
https://docs.contao.org/manual/de/anleitungen/die-erste-startseite/
https://docs.contao.org/manual/en/guides/add-first-index-page/

Please assign to myself ....

**Comment by netzarbeiter** [comment]
Is this issue still on your todo list?

**Comment by fkaminski** [comment]
With the current Contao demo you can reproduce and test the corresponding settings. 
Therefore I would close this now.
