### ISSUE TITLE
Image Links broken

### ISSUE THREAD

**Issue by fiedsch** [contao/docs#615]
The `en` screen shots introduced in #602 are broken in the generated pages. 

Not having installed hugo locally I did not test that (my bad). 

I created an `en` subdirectory to contain the english images and changed the path by switching from `de` to `en` which leads to (e.g.) `https://docs.contao.org/manual/en/installation/images/en/disable_cloud_resolver.png`. 

My first guess was that I forgot to include the images in the PR, but apparently I didn't as they they are in the repo: https://github.com/contao/docs/tree/master/docs/manual/installation/images/en

Do @fritzmg or @netzarbeiter see, what is wrong?

**Comment by netzarbeiter** [comment]
The correct path is `https://docs.contao.org/manual/de/installation/images/en/disable_cloud_resolver.png`.

Has been changed.
https://docs.contao.org/manual/en/installation/update-contao/

**Comment by fiedsch** [comment]
Thanks, Bjarke.

But does the image path‘s first `de` make sense? The path of the english page is https://docs.contao.org/manual/en/installation/update-contao/ with `en` at the respective place.

**Comment by netzarbeiter** [comment]
No, but is a (un)known limitation of our setup.
