### ISSUE TITLE
Remove references to pageModel request attribute

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#631]
See https://github.com/contao/docs/pull/629

**Comment by fritzmg** [comment]
@aschempp @leofeyer we must not forget to include this in the next public call 😁

**Comment by leofeyer** [comment]
https://github.com/contao/docs/pull/629#issuecomment-741635756:

> Sorry to say, but I still think this should not be added to the documentation. This would mean we promote it as a good practice to get the page object from the request. The reason it is there is for routing, not for users in a controller to retrieve it. Either use the controller argument resolver, or the ("officially supported") method added in Contao 4.9.10. 

As discussed in Mumble on December 17th, we want to keep the documentation but state that one should not directly use the request attribute.

**Comment by fritzmg** [comment]
Done in da1011a07b4948397cbad446a05b20fab0ed9918
