### ISSUE TITLE
Document "auto item"?

### ISSUE THREAD

**Issue by ameotoko** [contao/docs#632]
May be someone could cover (at least briefly) such concept as "auto item" in developer's docs? It feels like it is a common knowledge for core developers, but it doesn't seem to actually be documented anywhere...

**Comment by fritzmg** [comment]
I think I'll add this to the new _Routing_ section of the dev docs, where I can explain the "Legacy Routing" in more detail. Not just the `auto_item` is relevant there, but also how Contao automatically transforms a path to key => value pairs as pseudo query parameters.

**Comment by ameotoko** [comment]
I am sincerely looking forward to have this documentation😊

I can easily build a Symfony controller when needed, but sometimes one just need to use them "URL fragments" in Contao context)) for example in a classic List/Reader module pattern, or when your module acts something like Isotope's Checkout module with it's checkout steps. It would really help to have some best practices outlined.

**Comment by fritzmg** [comment]
@ameotoko is there anything in particular you'd like to know? That would help in figuring out what exactly we should document ;)
