### ISSUE TITLE
Gibt es das Wort "colorisieren"?

### ISSUE THREAD

**Issue by zonky2** [contao/docs#699]
siehe https://github.com/contao/docs/edit/main/docs/manual/guides/svg.de.md

m.E. gibt es "kolorieren"

**Comment by frontendschlampe** [comment]
kolorieren ist korrekt

**Comment by netzarbeiter** [comment]
Vielen Dank euch beiden, wurde korrigiert.
https://docs.contao.org/manual/de/anleitungen/svg/#svg-über-css-kolorieren
