### ISSUE TITLE
Lokale Generierung erzeugt keine relativen URIs

### ISSUE THREAD

**Issue by zonky2** [contao/docs#70]
**Affected version(s)**
* Hugo Static Site Generator v0.58.3-4AAC02D4 windows/amd64 BuildDate: 2019-09-19T15:29:19Z

**Description**
* Windows 7 U, lolakes Build
* alle Links sind absolut auf "https://docs.contao.org" gesetzt

**How to reproduce**  
* `hugo server --cleanDestinationDir --environment manual --destination ../build/manual --verbose`
* `/build` vorher gelehrt

**Comment by fritzmg** [comment]
Ich kann das leider nicht reproduzieren. Würde auch keinen Sinn machen, da die `baseURL` `https://docs.contao.org/...` einzig und allein über den command line parameter gesetzt wird.

**Comment by zonky2** [comment]
... o.k. - nochmal alles "clean" gemacht, neu generiert und Browsercache gelehrt => nu siehts gut aus!
