### ISSUE TITLE
Document, that panel order in DCAs matter

### ISSUE THREAD

**Issue by bezin** [contao/docs#701]
Hello there,

in a recent project we had the issue that `DC_Table` ignored our `filter`and `search` panels for the `limit` panel and back-end pagination.

You see in the screenshot a search by e-mail-address that results in three entries. The list (not visible here) contains those three entries, but the pagination and the ` panel still take all some hundred entries into account.

<img width="222" alt="2021-03-31 10_56_09" src="https://user-images.githubusercontent.com/4400435/113127851-82ba0980-9219-11eb-9d52-11329cd46fcf.png">

The panel configuration in this case was `limit;search;sort`. Because the search panel sets the actual search conditions and values, the limit menu rendered as no search took place. The limit menu then sets the limit for the pagination, hence the pagination is off, too. Defining the panels with `search;sort;limit` fixed this issue.

Conclusion is: The `limit` panel must come **after** `search` and `filter`. 

PR incoming. 

Cheers

**Comment by fritzmg** [comment]
That sounds like something that could be improved in Contao itself?

**Comment by bezin** [comment]
Yeah, you are probably right. I'll look into it

**Comment by bezin** [comment]
See https://github.com/contao/contao/issues/2932

**Comment by bezin** [comment]
This issue is obsolete, as soon as https://github.com/contao/contao/pull/2933 is merged 🎉
