### ISSUE TITLE
Dateiverwaltung Hinweis auf Backend-Einstellungen "Editierbare Dateien"

### ISSUE THREAD

**Issue by Mynyx** [contao/docs#71]
In https://docs.contao.org/manual/dateimanager/dateiverwaltung/ heißt es im Abschnitt "Die Navigationssymbole":
> **Datei bearbeiten:** Öffnet eine Eingabemaske zur Bearbeitung des Inhalts einer Datei mit einem Texteditor. Welche Dateien editiert werden dürfen, kannst du in den Backend-Einstellungen unter »Editierbare Dateien« festlegen.

Die Backend-Einstellungen "Editierbare Dateien" existiert in Contao 4.8 jedoch nicht mehr.

**Comment by Mynyx** [comment]
Siehe auch https://docs.contao.org/manual/user-management/benutzer/ in der Tabelle zu den erlaubten Datei-Operationen:
> Der Benutzer darf den Inhalt bestimmter Dateien mit dem Quelltexteditor direkt auf dem Server bearbeiten. Die erlaubten Dateien kannst du in den Backend-Einstellungen festlegen.

**Comment by netzarbeiter** [comment]
Es besteht eine Notiz die darauf hinweist.

https://docs.contao.org/manual/de/dateiverwaltung/dateien-und-ordner-verwalten/
