### ISSUE TITLE
English documentation hackathon

### ISSUE THREAD

**Issue by Toflar** [contao/docs#712]
We're trying get rid of as many `This article is machine translated` articles as possible.
For that cleanup, we're organizing a small hackathon where we meet on the [official Contao Slack](https://to.contao.org/slack) in the #english channel.
Everybody is more than welcome to join and spend as much time working with us as they want and can :)

Date and time: June 3rd - see official announcement https://contao.org/en/news/english-user-manual-hackathon.html

Process:

Ping me here or on Slack with your GitHub user name and an `UNASSIGNED` task number you would like to work on. I will assign it to you then by editing this description. That way, we don't do the work twice or more :-)

Here's the list of all the articles that need human attention:

- [x] https://docs.contao.org/manual/en/introduction/contao-quickstart/ (Task No. 1 - assigned to: @netzarbeiter)
- [x] https://docs.contao.org/manual/en/introduction/the-contao-network/ (Task No. 2 - assigned to: @netzarbeiter)
- [x] https://docs.contao.org/manual/en/introduction/contao-open-source-cms/ (Task No. 3 - assigned to: @MDevster)
- [x] https://docs.contao.org/manual/en/installation/install-contao/ (Task No. 4 - assigned to: @stefansl)
- [x] https://docs.contao.org/manual/en/installation/contao-manager/ (Task No. 5 - assigned to: @stefansl)
- [x] https://docs.contao.org/manual/en/installation/install-extensions/ (Task No. 6 - assigned to: @m-vo)
- [x] https://docs.contao.org/manual/en/administration-area/call-and-structure-of-the-backend/ (Task No. 7 - assigned to: @stefansl)
- [x] https://docs.contao.org/manual/en/installation/move-contao/ (Task No. 8 - assigned to: @stefansl @m-vo)
- [x] https://docs.contao.org/manual/en/installation/uninstalling-extensions/ (Task No. 9 - assigned to: @MDevster)
- [x] https://docs.contao.org/manual/en/installation/contao-installtool/ (Task No. 10 - assigned to: @Toflar)
- [x] https://docs.contao.org/manual/en/administration-area/list-data-records/ (Task No. 11 - assigned to: @stefansl)
- [x] https://docs.contao.org/manual/en/installation/update-extensions/ (Task No. 12 - assigned to: @MDevster)
- [x] https://docs.contao.org/manual/en/administration-area/edit-data-records/ (Task No. 13 - assigned to: @stefansl)
- [x] https://docs.contao.org/manual/en/layout/ (Task No. 14 - assigned to: @Toflar)
- [x] https://docs.contao.org/manual/en/layout/site-structure/ (Task No. 15 - assigned to: **UNASSIGNED**)
- [x] https://docs.contao.org/manual/en/layout/site-structure/pages-as-central-elements/ (Task No. 16 - assigned to: @Toflar)
- [x] https://docs.contao.org/manual/en/layout/site-structure/multi-domain-operation/ (Task No. 17 - assigned to: @Toflar)
- [x] https://docs.contao.org/manual/en/layout/theme-manager/manage-page-layouts/ (Task No. 18 - assigned to: @rburch)
- [x] https://docs.contao.org/manual/en/layout/module-management/ (Task No. 19 - assigned to: @netzarbeiter)
- [x] https://docs.contao.org/manual/en/layout/theme-manager/manage-stylesheets/ (Task No. 20 - assigned to: @netzarbeiter)
- [x] https://docs.contao.org/manual/en/layout/theme-manager/manage-themes/ (Task No. 21 - assigned to: @netzarbeiter)
- [x] https://docs.contao.org/manual/en/layout/module-management/navigation-modules/ (Task No. 22 - assigned to: @netzarbeiter)
- [x] https://docs.contao.org/manual/en/layout/module-management/user-modules/ (Task No. 23 - assigned to: @netzarbeiter)
- [x] https://docs.contao.org/manual/en/layout/theme-manager/ (Task No. 24 - assigned to: @asconsulting)
- [x] https://docs.contao.org/manual/en/layout/module-management/miscellaneous/ (Task No. 25 - assigned to: @fiedsch)
- [x] https://docs.contao.org/manual/en/article-management/ (Task No. 26 - assigned to: @fiedsch)
- [x] https://docs.contao.org/manual/en/layout/module-management/applications/ (Task No. 27 - assigned to: @netzarbeiter)
- [x] https://docs.contao.org/manual/en/layout/templates/template-inheritance/ (Task No. 28 - assigned to: @m-vo)
- [x] https://docs.contao.org/manual/en/layout/templates/template-data/ (Task No. 29 - assigned to: @m-vo)
- [x] https://docs.contao.org/manual/en/layout/templates/template-assets/ (Task No. 30 - assigned to: @m-vo)
- [x] https://docs.contao.org/manual/en/layout/templates/manage-template/ (Task No. 31 - assigned to: @m-vo)
- [x] https://docs.contao.org/manual/en/layout/templates/template-insertion/ (Task No. 32 - assigned to: @m-vo)
- [x] https://docs.contao.org/manual/en/layout/module-management/website-search/ (Task No. 33 - assigned to: @Toflar)
- [x] https://docs.contao.org/manual/en/article-management/articles/ (Task No. 34 - assigned to: @fiedsch)
- [x] https://docs.contao.org/manual/en/article-management/insert-tags/ (Task No. 35 - assigned to: @Toflar)
- [x] https://docs.contao.org/manual/en/core-extensions/calendar/calendar-management/ (Task No. 36 - assigned to: @netzarbeiter)
- [x] https://docs.contao.org/manual/en/core-extensions/news/ (Task No. 37 - assigned to: @rburch)
- [x] https://docs.contao.org/manual/en/core-extensions/calendar/frontend-modules/ (Task No. 38 - assigned to: @rburch)
- [x] https://docs.contao.org/manual/en/core-extensions/news/news-management/ (Task No. 39 - assigned to: @rburch)
- [x] https://docs.contao.org/manual/en/core-extensions/news/frontend-modules/ (Task No. 40 - assigned to: @netzarbeiter)
- [x] https://docs.contao.org/manual/en/core-extensions/calendar/ (Task No. 41 - assigned to: @netzarbeiter)
- [x] https://docs.contao.org/manual/en/article-management/content-elements/ (Task No. 42 - assigned to: @fiedsch )
- [x] https://docs.contao.org/manual/en/core-extensions/faq/faq-management/ (Task No. 43 - assigned to: @MDevster)
- [x] https://docs.contao.org/manual/en/core-extensions/faq/frontend-modules/ (Task No. 44 - assigned to: @netzarbeiter)
- [x] https://docs.contao.org/manual/en/core-extensions/newsletter/newsletter-management/ (Task No. 45 - assigned to: @blairwinans)
- [x] https://docs.contao.org/manual/en/core-extensions/faq/ (Task No. 46 - assigned to: @Toflar)
- [x] https://docs.contao.org/manual/en/core-extensions/newsletter/ (Task No. 47 - assigned to: @blairwinans)
- [x] https://docs.contao.org/manual/en/core-extensions/newsletter/frontend-modules/ (Task No. 48 - assigned to: @blairwinans)
- [x] https://docs.contao.org/manual/en/file-manager/ (Task No. 49 - assigned to: @blairwinans)
- [x] https://docs.contao.org/manual/en/file-manager/file-manager/ (Task No. 50 - assigned to: @blairwinans)
- [x] https://docs.contao.org/manual/en/file-manager/meta-data/ (Task No. 51 - assigned to: @blairwinans)
- [x] https://docs.contao.org/manual/en/file-manager/control-downloads/ (Task No. 52 - assigned to: @blairwinans)
- [x] https://docs.contao.org/manual/en/extensions/contao-easy_themes/ (Task No. 53 - assigned to: @netzarbeiter)
- [x] https://docs.contao.org/manual/en/extensions/isotope-core/ (Task No. 54 - assigned to: @netzarbeiter)

**Comment by stefansl** [comment]
@Toflar @fritzmg Assign me to task no. 7 and 13, please. Today I had some time to edit that pages ... :)

**Comment by MDevster** [comment]
Assign me to task no. 3, 9, 12 and 43, please.

**Comment by fiedsch** [comment]
please assign me to no. 25 (to start with).

**Comment by stefansl** [comment]
Assign me to no. 4 and 5, pls :)

**Comment by rburch** [comment]
37, 38, 39 pls

**Comment by fiedsch** [comment]
As mentioned in Slack No. 26 for me please. I'm halfway through and will finish the PR tomorrow when my head is working properly again.

**Comment by asconsulting** [comment]
Assign me 20, 21, 22, 23 please.

**Comment by m-vo** [comment]
I'm yet again amazed what the OSS culture can achieve. Big up to everybody! ❤️

**Comment by stjeanmark** [comment]
It's been a long week. I will take on my assigned task tomorrow, Saturday, and see what's left to be done.

**Comment by Toflar** [comment]
@rburch @asconsulting @stjeanmark friendly reminder 😊

**Comment by rburch** [comment]
Thank you! I’ll do it this week.

Bob

Bob Burch
Bright Cloud Studio
Westfield, MA
413.885.0378
***@***.*** ***@***.***>
brightcloudstudio.com <https://www.brightcloudstudio.com/>

**Comment by netzarbeiter** [comment]
@rburch, @asconsulting and @stjeanmark when will you take up the tasks?

**Comment by netzarbeiter** [comment]
It is done. Thank you to all participants.
