### ISSUE TITLE
Remove characterSet from localconfig

### ISSUE THREAD

**Issue by ausi** [contao/docs#769]
Remove `characterSet` from https://docs.contao.org/manual/de/system/einstellungen/#localconfig once https://github.com/contao/contao/pull/3056 got merged.

Also add documentation for `config.uploadPath` and `config.editableFileTypes` for `DC_Folder`.

**Comment by fritzmg** [comment]
Well we cannot remove it altogether, since it is still present in Contao 4.9, is it not? And does `characterSet` really not work at all? I thought it should work, if you

* Configured the database correctly.
* Configured the database connection correctly.
* Configured the `characterSet` correctly.

**Comment by Toflar** [comment]
It really did not work at all: https://github.com/contao/contao/issues/3050#issuecomment-854714950

**Comment by ausi** [comment]
> Well we cannot remove it altogether, since it is still present in Contao 4.9, is it not?

Agree, we should note that it is deprecated and that it should not be used (regardless of the Contao version IMO).

**Comment by ausi** [comment]
Closed in favor of #777 and #778
