### ISSUE TITLE
The document root is changed from `web` to `public`

### ISSUE THREAD

**Issue by leofeyer** [contao/docs#776]
As of Contao 4.12, the default document root will be `public` instead of `web` (see https://github.com/contao/contao/issues/1088 for an explanation). If a `web` folder exists, Contao automatically uses it instead of the default folder to ensure backwards compatibility.

**Comment by netzarbeiter** [comment]
Passt diese Formulierung:

({{< version-tag "4.12" >}} Dem Standard vom Symfony folgend, wurde der öffentlich erreichbare Unterordner von `/web` in `/public` umbenannt. Falls in deiner Installation ein Verzeichnis `/web` existiert, wird dieses von Contao automatisch anstelle von `/public` verwendet.)

**Comment by fritzmg** [comment]
Das passt so, ja 👍

**Comment by netzarbeiter** [comment]
https://github.com/contao/docs/pull/833
