### ISSUE TITLE
Seite Mitglieder Abschnitt Home-Verzeichnis

### ISSUE THREAD

**Issue by Mynyx** [contao/docs#78]
Auf der Seite Mitglieder enthält der Abschnitt Home-Verzeichnis Schreibfehler:
>**Ein Home-Verzeichnis festlegen:** Hier aktivierst du das ein eigenes Verzeichnis.
> **Home-Verzeichnis:** Hier legst du das Ordner des Mitglieds fest.

**Comment by netzarbeiter** [comment]
https://github.com/contao/docs/commit/acf5251460bc93c33b952571e2848b914eb48fe7
