### ISSUE TITLE
Add Information about the Allowed HTML attributes setting

### ISSUE THREAD

**Issue by ausi** [contao/docs#807]
We should add Information about the new “Allowed HTML attributes” setting to https://docs.contao.org/manual/de/system/einstellungen/#sicherheitseinstellungen

Related: https://community.contao.org/de/showthread.php?81419

**Comment by netzarbeiter** [comment]
The information about the new “Allowed HTML attributes” has been added.

- https://docs.contao.org/manual/en/system/settings/#security-settings
- https://docs.contao.org/manual/de/system/einstellungen/#sicherheitseinstellungen
