### ISSUE TITLE
DCA folder does not exist anymore

### ISSUE THREAD

**Issue by modir** [contao/docs#825]
At the moment all documentation related to DCA write that you need to save this file in the folder contao/dca but this folder does not exist anymore. e.g. https://docs.contao.org/dev/reference/dca/config/

Where do we need to save the files now? I would change the documentation if I would know where to save it now.

Furthermore I assume that there is now a new procedure how to then create the tables. Or do I still have to start the installer again?

**Comment by fritzmg** [comment]
> but dies folder does not exist anymore

Those folders never existed, you will always have to create them yourself. See https://docs.contao.org/dev/getting-started/starting-development/#structure »

> When customizing your web application, the following files and folders will usually be of interest. **Some of those will need to be created manually**:

---

> Furthermore I assume that there is now a new procedure how to then create the databases. Or do I still have to start the installer again?

Not sure what you mean? Contao cannot create the actual database for you (and was never able to). This is something you have to do with your database management tool (e.g. phpMyAdmin, your hoster's control panel, Sequel Pro, SQLyog, etc.). If you are looking for the information which character set and default collation your newly created database should have: this is something we should indeed document better. The recommended charset is `utf8mb4` and the recommended collation is `utf8mb4_unicode_ci` (those are the recommendations for any database, not just Contao).

**Comment by fritzmg** [comment]
> Contao cannot create the actual database for you (and was never able to)

Actually, after you installed Contao and already configured the database credentials (via `parameters.yml` or `.env.local`) you can run the following command to automatically create the database (without any tables) for you:

```
vendor/bin/contao-console doctrine:database:create
```

**Comment by modir** [comment]
Sorry, I was writing too fast. I ment "tables" not "databases".

**Comment by modir** [comment]
The developer documentation is here telling me something totally different than the end user documentation I linked to. I am talking here from end user perspective when I only want to save some form data into a table. According to the documentation I linked to I only need to create a simple file in a DCA folder.

**Comment by fritzmg** [comment]
> Sorry, I was writing too fast. I ment "tables" not "databases".

Alright, then yes, you can either still use the Install Tool or the `contao:migrate` command. See https://docs.contao.org/manual/en/installation/install-contao/#update-database-tables-1

> The developer documentation is here telling me something totally different than the end user documentation I linked to.

You linked to the developer documentation … what is totally different?

> According to the documentation I linked to I only need to create a simple file in a DCA folder.

Yes, that is what you need to do.

**Comment by modir** [comment]
Just so you know where I am coming from. I was at the page https://docs.contao.org/manual/de/formulargenerator/formulare/#formulardaten-speichern about the form generator and now I "only" want to create a simple table to write form data into.

**Comment by fritzmg** [comment]
> Just so you know where I am coming from. I was at the page https://docs.contao.org/manual/de/formulargenerator/formulare/#formulardaten-speichern about the form generator and now I "only" want to create a simple table to write form data into.

Personally I would recommend to use [terminal42/contao-leads](https://extensions.contao.org/?p=terminal42%2Fcontao-leads) for this kind of task, unless you have a specific reason for creating your own table.

**Comment by modir** [comment]
Well, one of the reason is that we already have the form and it is quite complicated.
![Screenshot from 2021-09-11 14-02-03](https://user-images.githubusercontent.com/2803913/132947260-ef6c2b15-7f9e-425a-b5ac-4e86a20cc7e5.png)

But back to my initial question. All examples about DCA tell me to save the files in contao/dca (see screenshot). So where do I have to save it these days? I think this part of the documentation is still from contao 3.x. Do I have to generate a new extension just for this DCA file now?

**Comment by fritzmg** [comment]
> So where do I have to save it these days?

That _is_ the path where you save it.

> I think this part of the documentation is still from contao 3.x.

No, in Contao 3 you did it in either `system/config/dcaconfig.php` or in `system/modules/<your-modul>/contao/dca/…`.

> Do I have to generate a new extension just for this DCA file now?

No, you do not have to do that.

**Comment by modir** [comment]
I found now the answer in the documentation you linked. It is now app/Resources/contao/

**Comment by fritzmg** [comment]
> It is now app/Resources/contao/

That is only the case, if you still use Contao 4.4 (which has reached the end of its active support life and is now in security support mode only). If you use Contao 4.9 or higher, the folder is `contao/`.

**Comment by modir** [comment]
OK. good to know. Thanks for the fast help
