### ISSUE TITLE
Guide: Show an alternative approach to the Contao CSS framework with CSS Grid Layout

### ISSUE THREAD

**Issue by fkaminski** [contao/docs#832]
Based on the following options with CSS Grid Layout:
"[grid-area](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-area)" / "[grid-template-areas](https://developer.mozilla.org/de/docs/Web/CSS/grid-template-areas)" / "[grid-template-columns](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns)" /  "[grid-template-rows](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-rows)" ... 

(For me as a reminder: https://github.com/contao/contao/issues/3235)

Please assign to myself

**Comment by fkaminski** [comment]
Maybe not necessary anymore: See "[Contao Show #12](https://www.youtube.com/watch?v=sKy7T2J2tpg)"
?

**Comment by netzarbeiter** [comment]
What about adding a link to the Contao Show #12?

Die Contao Show hat das Thema [Inhalte mehrspaltig in Contao umsetzen](to.contao.org/tv/show/12) behandelt.
