### ISSUE TITLE
Document Response Context

### ISSUE THREAD

**Issue by richardhj** [contao/docs#837]
It looks like that the Response Context that was finalized in contao/contao#3066 is not documented yet.
This issue shall keep track of the status.

**Comment by Toflar** [comment]
It is: https://github.com/contao/docs/pull/784

**Comment by Toflar** [comment]
@fritzmg just never merged :D

**Comment by fritzmg** [comment]
Woops, got lost in my sea of GitHub emails 🙈. Merged now.
