### ISSUE TITLE
link::back insert tag is deprecated

### ISSUE THREAD

**Issue by ausi** [contao/docs#859]
`back` ist deprecated for all `link_*` insert tags (since contao 4.9.22), see https://github.com/contao/contao/pull/3585

**Comment by bezin** [comment]
I am sorry for the unrelated references. I made a faulty `push` to my fork 🙄

**Comment by jochi44** [comment]
As discussed in https://github.com/contao/contao/issues/6785#issuecomment-1911653307 the deprecation of `{{link::back}}` should be documented in the user manual.

**Comment by Toflar** [comment]
@jochi44 would you try to contribute this to the docs yourself? 😊 https://docs.contao.org/manual/en/contributing/
