### ISSUE TITLE
Text color of search box

### ISSUE THREAD

**Issue by fiedsch** [contao/docs#879]
On an iOS (tested on iPad, but likely also on iPhone) the text in the search box is "white on white" as the `<input>`s background is not orange. 

Adding 
```
-webkit-text-fill-color: rgb(244,124,0);
```
to `.algolia-searchbox input[type="search"]` solved that in my tests. 

I'd like to make a PR, but someone has to point me to the location of the corresponding theme file please.

**Comment by netzarbeiter** [comment]
https://github.com/contao/docs/tree/main/page/static/css

**Comment by fritzmg** [comment]
> I'd like to make a PR, but someone has to point me to the location of the corresponding theme file please.

https://github.com/contao/docs/blob/1a6b75d87c45fc0ed5f1024c3eecd81bf5e8f08b/page/static/css/theme-contao.css#L473-L540 :)

**Comment by fiedsch** [comment]
`-webkit-appearance:none` worked in my first tests without breaking the non-iOS browser's display. I will do some more research on the topic before making another PR though.

Relates to [this setting](https://github.com/matcornic/hugo-theme-learn/blob/e817f53d690d35f181c896e0e320cb40f797e88c/static/css/nucleus.css#L147) but might "just" be an iOS bug as discussed [here](https://theme.co/forum/t/cant-seem-to-change-webkit-appearance-for-search-field/94147) or [here](https://bugs.webkit.org/show_bug.cgi?id=229883).

**Comment by fiedsch** [comment]
Solved in #921
