### ISSUE TITLE
Add a new Guide for using Twig

### ISSUE THREAD

**Issue by fkaminski** [contao/docs#915]
A more detailed Guide using the Twig features with practical examples.

Please asign to myself

**Comment by fkaminski** [comment]
Contributions for the manual should be Contao specific.
Basic Twig support is covered in #914. This topic would be more general (Twig possibilities are [documented](https://twig.symfony.com/doc/3.x/)).

Shall we therefore close this (Possibly something for a forum post).

**Comment by fritzmg** [comment]
I am not sure what your plan was here. Generally Twig is already documented of course, so you just have to link to that documentation. You can of course still document some basics may be.

**Comment by fiedsch** [comment]
I'm with @fritzmg on this one. Maybe a short teaser that shows some really nice features of Twig might be helpful for users that might think "why do I have to learn something new again" because the do not (yet) see the benefits.

**Comment by fkaminski** [comment]
> ... because the do not (yet) see the benefits.

That was the idea. I'll think about what would be useful in this regard. Since I will try this for me anyway: A future pull request or draft, for the purpose of better assessment, can always be rejected later.

**Comment by fkaminski** [comment]
Closed this because of PR #1176 (or https://docs.contao.org/dev/framework/templates/getting-started/)
