### ISSUE TITLE
Document front end preview

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#923]
See https://github.com/contao/contao/pull/3872#discussion_r778001098

* Document front end preview and its inner workings in general.
* Document `BE_USER_LOGGED_IN` and its actual meaning.
* Document the new way and the deprecation of the constant.

I would put it into a subsection of _Security_.

**Comment by Toflar** [comment]
@fritzmg this is the last one to close 4.13, do you still plan to document this? 😊
