### ISSUE TITLE
Document layout inheritance 

### ISSUE THREAD

**Issue by fkaminski** [contao/docs#935]
| Info: |  |
| --- | --- |
| see Issue/PR: | [#3419](https://github.com/contao/contao/pull/3419) |
| Milestone: | 4.13.0 |

**Comment by fritzmg** [comment]
You don't have to create a PR _and_ an issue. Just one or the other ;)

**Comment by fkaminski** [comment]
Oh, thought it was necessary for the purpose of overview ...
