### ISSUE TITLE
Add Guide: Annual overview with separate mini calendar

### ISSUE THREAD

**Issue by fkaminski** [contao/docs#949]
| Issue | 
| --- |
| see [#3236](https://github.com/contao/contao/issues/3236) |

As mentioned in the issue I would like to test this alternative calendar display and describe it in a guide.
Together with the "[Save form data](https://docs.contao.org/manual/en/guides/save-form-data/)" it would be another helpful implementation (e.g. availability/apartment) without extension needs.

Please assign to me

**Comment by fritzmg** [comment]
If you mean my suggestion in that ticket: that's not really something that should be integrated into the official manual, as using `Input::setGet` this way should not really be recommended. It is just meant to be a way of implementing a specific requirement with the least amount of work possible (while still adhering to some proper coding standards at least a little) 😉 

The proper way of doing this would be to develop your own module that does exactly what you need. And that cannot be covered by either the dev docs nor the manual.

**Comment by fkaminski** [comment]
OK, closing this because of above comment.
Thank you.
