### ISSUE TITLE
Add note to PHP version documentation about Contao 4.9 and PHP8 compatability

### ISSUE THREAD

**Issue by FelixOliverLange** [contao/docs#973]
Hi Contao team, 

I noticed that the docs imply that Contao 4.9, as LTS release, supports PHP 8.
I attempted the upgrade from PHP 7.3 to PHP 8.0 and ran into an issue that, while it is resolvable, may not be apparent to a normal user. 

The issue comes up when attemting to use Contao 4.9.22 with PHP 8.0. While Contao itself will run, updates of e.g. Contao to 4.9.24 via the contao manager will not, as the dependency lcobucci/jwt of contao-core is locked to version 3.4.6, [which does not support PHP 8](https://packagist.org/packages/lcobucci/jwt#3.4.6). This prevents:
* Updating Contao, e.g. for security fixes
* removing other packages, e.g. due to incompatability with PHP 8 found later (in my case that was the a [cookiebar extension](https://packagist.org/packages/codefog/contao-cookiebar))

as in both cases, composer will fail stating that lcobucci/jwt does not support PHP 8. 

This can be resolved by:
* reverting back to PHP 7
* updating Contao to version 4.9.24 (as that bumps the JWT library to version 4.0.4 [which supports JWT](https://packagist.org/packages/lcobucci/jwt#4.0.4)) and removing packages not compatible with PHP 8
* switching back to PHP 8

While that's a fairly easy fix, it requires investigating said JWT library and its compatibility - and the knowledge that Contao 4.9.24 bumps this version. So maybe adding a statement to the [4.9 PHP system requirements section](https://docs.contao.org/manual/de/installation/systemvoraussetzungen/#contao-4-9-lts), explaining that the latest version of Contao 4.9 must be installed before the update, may help users. As some hosters prevent switching back to old PHP versions after an update, users may otherwise be locked into a state where they are on PHP 8 and would need to switch back temporarily but can't. As of now I don't have the feeling that the docs make this explicit, it may be an implicit assumption. 

Thanks a lot for all your work and for making Contao 4.9 compatible with PHP 8!

**Comment by fritzmg** [comment]
> I noticed that the docs imply that Contao 4.9, as LTS release, supports PHP 8.

Yes, Contao 4.9 officially supports PHP 8 (see also [here](https://github.com/contao/contao/blob/4.9.24/core-bundle/composer.json#L18)).

> Contao to 4.9.24 via the contao manager will not, as the dependency lcobucci/jwt of contao-core is locked to version 3.4.6

No, the dependency is not locked to version 3.4.6 (see [here](https://github.com/contao/contao/blob/4.9.24/core-bundle/composer.json#L58)). You likely did not run a full composer update after switching to PHP 8. You can run a full composer update under the "maintenance" section of the Contao Manager.

![image](https://user-images.githubusercontent.com/4970961/151700902-1749b966-d548-4259-b506-fe549bd48442.png)

**Comment by fritzmg** [comment]
> As some hosters prevent switching back to old PHP versions after an update, users may otherwise be locked into a state where they are on PHP 8 and would need to switch back temporarily but can't.

Btw., that's an issue in any case. For example an extension or other dependency that you might want to install _later on_ might not yet support PHP 8 and thus you might have to switch back to PHP 7.4 - even though Contao itself fully supports PHP 8.

**Comment by FelixOliverLange** [comment]
thanks for the feedback, much appreciated. Would a statement about the full composer update maybe help then?

**Comment by fritzmg** [comment]
> Would a statement about the full composer update maybe help then?

Absolutely :). PR: #974
