### ISSUE TITLE
Seitennavigation auf bestimmte Headlines begrenzen

### ISSUE THREAD

**Issue by fkaminski** [contao/docs#98]
Mir ist aufgefallen, das in der oberen Seitennavigation alle Headline der Seite aufgenommen werden. Zum Beispiel in "Inhaltselemente". Hier werden die Unter Überschriften des Markdown Kapitels ebenfalls aufgeführt - s. Screen.

Evtl. könnte man dies auf nur einige Markdown Headline beschränken.

![docs 15](https://user-images.githubusercontent.com/7679799/67005338-a9968580-f0e2-11e9-9ea5-59e4a4ae0efb.png)

**Comment by netzarbeiter** [comment]
Das ist so gewollt, da es sich dabei auch um eine Einfühurng in die Syntax von Markdown handelt.

**Comment by fkaminski** [comment]
Ok, wie kann ich dann aber generell mit Headline im Markdown arbeiten/strukturieren ohne das diese in der Navi auftauchen.

**Comment by fritzmg** [comment]
Das ist nicht vorgesehen.

**Comment by netzarbeiter** [comment]
Warum sollte eine Headline nicht in der Navi auftauchen?

**Comment by fkaminski** [comment]
Habt schon Recht - dachte halt zum strukturieren eines Textes mit Sub Header ala 
###Sub1 
####Sub4 
müßten diese ja nicht unbedingt in der Navi übernommen werden ...
Aber OK - Danke

**Comment by fritzmg** [comment]
Du könntest ja ein Ticket im Theme dafür öffnen, dass man das zB konfigurierbar machen kann.

Heißt aber nicht, das wir das dann auch unbedingt so implementieren wollen ;)
