### ISSUE TITLE
LTS descriptions are wrong

### ISSUE THREAD

**Issue by Toflar** [contao/docs#981]
https://docs.contao.org/manual/en/installation/update-contao/#long-term-support-versions

**Comment by netzarbeiter** [comment]
Taken from here: https://de.wikipedia.org/wiki/Contao#Long-Term-Support-Version

Is only 24 month wrong?

**Comment by Toflar** [comment]
I just added the issue because it still mentioned Contao 2.11 which does not make a lot of sense so I think we should restructure this a bit. But yes, it's also wrong. We have a total of 4 years :) 

- Half a year of active support like for any version
- Plus 2.5 years of LTS
- Plus 1 year of extended LTS aka security-only mode

**Comment by netzarbeiter** [comment]
https://github.com/contao/docs/pull/986
